package runtime

import (
	"fmt"
	"sort"
	"strings"

	"github.com/okedeji/mcpvessel/internal/vesselfile"
)

// dockerfileInput is the parameter object for generateDockerfile.
type dockerfileInput struct {
	Vesselfile *vesselfile.Vesselfile

	// Labels become OCI image labels; empty values are skipped.
	Labels map[string]string
}

// generateDockerfile produces the Dockerfile the dockerfile.v0 frontend
// parses. Vesselfile directives pass through; ENTRYPOINT cmd becomes
// ENTRYPOINT ["sh", "-c", "cmd"], and codegen injects WORKDIR /agent,
// COPY . /agent, and provenance labels. Output is byte-deterministic for the
// same input: BuildKit's cache key hashes it.
func generateDockerfile(in dockerfileInput) string {
	af := in.Vesselfile
	var b strings.Builder

	fmt.Fprintf(&b, "# Auto-generated by mcpvessel. Do not edit.\n")
	fmt.Fprintf(&b, "# syntax=docker/dockerfile:1\n\n")

	fmt.Fprintf(&b, "FROM %s\n", af.From)
	fmt.Fprintf(&b, "WORKDIR /agent\n")

	// RUNs come before the source COPY: deps like "RUN pip install mcp" have
	// no inputs in the source tree, so editing agent.py busts only the cheap
	// COPY layer, not the expensive install. Trade-off: "RUN pip install -r
	// requirements.txt" breaks (the file is not in the image yet); the
	// mcpvessel convention is to inline deps in RUN.
	for _, cmd := range af.Run {
		fmt.Fprintf(&b, "RUN %s\n", cmd)
	}

	fmt.Fprintf(&b, "COPY . /agent\n")

	// Stable ENV order keeps BuildKit's cache key stable across rebuilds.
	keys := sortedKeys(af.Env)
	for _, k := range keys {
		// An empty value is a required operator input, not a default of
		// empty. Baking it would mask the fail-closed check; the runtime
		// injects it from the operator pool instead.
		if af.Env[k] == "" {
			continue
		}
		fmt.Fprintf(&b, "ENV %s=%s\n", k, dockerfileEscapeEnv(af.Env[k]))
	}

	// LABEL keys are namespaced io.mcpvessel.* to stay clear of conventional
	// OCI labels (org.opencontainers.image.*).
	for _, k := range sortedKeys(in.Labels) {
		v := in.Labels[k]
		if v == "" {
			continue
		}
		fmt.Fprintf(&b, "LABEL %s=%s\n", k, dockerfileQuote(v))
	}

	// Exec form runs the argv directly, so an agent can sit on a distroless
	// base with no shell. A shell-form ENTRYPOINT is a single command string
	// and needs sh -c to run it, the same split Dockerfile draws.
	if len(af.EntrypointExec) > 0 {
		fmt.Fprintf(&b, "ENTRYPOINT [%s]\n", jsonStringArray(af.EntrypointExec))
	} else {
		fmt.Fprintf(&b, "ENTRYPOINT [\"sh\", \"-c\", %s]\n", dockerfileQuote(af.Entrypoint))
	}

	return b.String()
}

// jsonStringArray renders argv as the comma-separated body of a JSON array,
// each element quoted the way the Dockerfile parser accepts.
func jsonStringArray(argv []string) string {
	quoted := make([]string, len(argv))
	for i, a := range argv {
		quoted[i] = dockerfileQuote(a)
	}
	return strings.Join(quoted, ", ")
}

func sortedKeys(m map[string]string) []string {
	if len(m) == 0 {
		return nil
	}
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// dockerfileQuote returns s in JSON-string form (Go's %q matches JSON syntax
// for ASCII), the shape the Dockerfile parser accepts for LABEL values and
// JSON-form ENTRYPOINT arguments.
func dockerfileQuote(s string) string {
	return fmt.Sprintf("%q", s)
}

// dockerfileEscapeEnv quotes an ENV value only when it contains whitespace or
// specials; Dockerfile's KEY=value form otherwise reads the value to newline.
func dockerfileEscapeEnv(v string) string {
	if !strings.ContainsAny(v, " \t\"\\") {
		return v
	}
	return dockerfileQuote(v)
}
