"""Sub-agent call helpers.

A USES directive in the Agentfile makes a sub-agent reachable by name:

    result = agentcage.agents.web_search.search(query="agentic memory")

The runtime exposes each USES'd sub-agent over its own MCP endpoint
and injects the URL as AGENTCAGE_USES_<NAME>_URL (uppercased, dashes
become underscores). Calling the proxy issues the MCP request
synchronously and returns the text response.

Attribute access is dynamic, so misspelled names raise at call time,
not at import. IDE autocomplete arrives via type stubs generated by
`agentcage sync`, which reads each sub-agent's manifest and writes
.agentcage/uses.pyi into the source tree. Run sync after editing USES
and the IDE sees typed methods on every sub-agent.

To skip the SDK, read AGENTCAGE_USES_<NAME>_URL and construct an mcp
ClientSession directly.
"""

from __future__ import annotations

import asyncio
import os
from typing import Any


def _env_var_for(name: str) -> str:
    """Return the env var name the runtime uses for a sub-agent."""
    return f"AGENTCAGE_USES_{name.upper().replace('-', '_')}_URL"


class _ToolProxy:
    """Callable bound to one tool on one sub-agent."""

    def __init__(self, agent_name: str, url: str, tool_name: str):
        self._agent = agent_name
        self._url = url
        self._tool = tool_name

    def __call__(self, **kwargs: Any) -> str:
        return asyncio.run(self._invoke(kwargs))

    async def _invoke(self, args: dict) -> str:
        # Imported lazily so that constructing the namespace does not
        # pull mcp's network code paths until an author actually calls
        # a sub-agent.
        from mcp import ClientSession
        from mcp.client.streamable_http import streamable_http_client

        async with streamable_http_client(self._url) as (read, write, _):
            async with ClientSession(read, write) as session:
                await session.initialize()
                result = await session.call_tool(self._tool, args)
                for block in result.content:
                    if getattr(block, "type", None) == "text":
                        return block.text
                return ""


class _SubAgent:
    """Lazy MCP client for one USES'd sub-agent.

    The URL is resolved on first tool access, not at construction, so a
    missing AGENTCAGE_USES_<NAME>_URL surfaces at the call site instead
    of at module import.
    """

    def __init__(self, name: str):
        self._name = name
        self._url: str | None = None

    def _resolve_url(self) -> str:
        if self._url is None:
            env = _env_var_for(self._name)
            url = os.environ.get(env)
            if not url:
                raise RuntimeError(
                    f"sub-agent {self._name!r} not available: "
                    f"add 'USES @org/{self._name}:VERSION' to the Agentfile "
                    f"(expected env var {env})"
                )
            self._url = url
        return self._url

    def __getattr__(self, tool_name: str) -> _ToolProxy:
        return _ToolProxy(self._name, self._resolve_url(), tool_name)


class _AgentsNamespace:
    """Attribute access yields a _SubAgent for any name."""

    def __getattr__(self, name: str) -> _SubAgent:
        return _SubAgent(name)


# Module-level singleton exposed as agentcage.agents.
agents = _AgentsNamespace()
