// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/audit.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditService_VerifyChain_FullMethodName        = "/agentcage.audit.v1.AuditService/VerifyChain"
	AuditService_GetEntries_FullMethodName         = "/agentcage.audit.v1.AuditService/GetEntries"
	AuditService_GetEntry_FullMethodName           = "/agentcage.audit.v1.AuditService/GetEntry"
	AuditService_GetDigest_FullMethodName          = "/agentcage.audit.v1.AuditService/GetDigest"
	AuditService_ExportCage_FullMethodName         = "/agentcage.audit.v1.AuditService/ExportCage"
	AuditService_ListCagesWithAudit_FullMethodName = "/agentcage.audit.v1.AuditService/ListCagesWithAudit"
	AuditService_GetKeyVersions_FullMethodName     = "/agentcage.audit.v1.AuditService/GetKeyVersions"
	AuditService_ChainStatus_FullMethodName        = "/agentcage.audit.v1.AuditService/ChainStatus"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditServiceClient interface {
	VerifyChain(ctx context.Context, in *VerifyChainRequest, opts ...grpc.CallOption) (*VerifyChainResponse, error)
	GetEntries(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error)
	GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error)
	GetDigest(ctx context.Context, in *GetDigestRequest, opts ...grpc.CallOption) (*GetDigestResponse, error)
	ExportCage(ctx context.Context, in *ExportCageRequest, opts ...grpc.CallOption) (*ExportCageResponse, error)
	ListCagesWithAudit(ctx context.Context, in *ListCagesWithAuditRequest, opts ...grpc.CallOption) (*ListCagesWithAuditResponse, error)
	GetKeyVersions(ctx context.Context, in *GetKeyVersionsRequest, opts ...grpc.CallOption) (*GetKeyVersionsResponse, error)
	ChainStatus(ctx context.Context, in *ChainStatusRequest, opts ...grpc.CallOption) (*ChainStatusResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) VerifyChain(ctx context.Context, in *VerifyChainRequest, opts ...grpc.CallOption) (*VerifyChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyChainResponse)
	err := c.cc.Invoke(ctx, AuditService_VerifyChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetEntries(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (*GetEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntriesResponse)
	err := c.cc.Invoke(ctx, AuditService_GetEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntryResponse)
	err := c.cc.Invoke(ctx, AuditService_GetEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetDigest(ctx context.Context, in *GetDigestRequest, opts ...grpc.CallOption) (*GetDigestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDigestResponse)
	err := c.cc.Invoke(ctx, AuditService_GetDigest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ExportCage(ctx context.Context, in *ExportCageRequest, opts ...grpc.CallOption) (*ExportCageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportCageResponse)
	err := c.cc.Invoke(ctx, AuditService_ExportCage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ListCagesWithAudit(ctx context.Context, in *ListCagesWithAuditRequest, opts ...grpc.CallOption) (*ListCagesWithAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCagesWithAuditResponse)
	err := c.cc.Invoke(ctx, AuditService_ListCagesWithAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetKeyVersions(ctx context.Context, in *GetKeyVersionsRequest, opts ...grpc.CallOption) (*GetKeyVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyVersionsResponse)
	err := c.cc.Invoke(ctx, AuditService_GetKeyVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) ChainStatus(ctx context.Context, in *ChainStatusRequest, opts ...grpc.CallOption) (*ChainStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChainStatusResponse)
	err := c.cc.Invoke(ctx, AuditService_ChainStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility.
type AuditServiceServer interface {
	VerifyChain(context.Context, *VerifyChainRequest) (*VerifyChainResponse, error)
	GetEntries(context.Context, *GetEntriesRequest) (*GetEntriesResponse, error)
	GetEntry(context.Context, *GetEntryRequest) (*GetEntryResponse, error)
	GetDigest(context.Context, *GetDigestRequest) (*GetDigestResponse, error)
	ExportCage(context.Context, *ExportCageRequest) (*ExportCageResponse, error)
	ListCagesWithAudit(context.Context, *ListCagesWithAuditRequest) (*ListCagesWithAuditResponse, error)
	GetKeyVersions(context.Context, *GetKeyVersionsRequest) (*GetKeyVersionsResponse, error)
	ChainStatus(context.Context, *ChainStatusRequest) (*ChainStatusResponse, error)
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServiceServer struct{}

func (UnimplementedAuditServiceServer) VerifyChain(context.Context, *VerifyChainRequest) (*VerifyChainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyChain not implemented")
}
func (UnimplementedAuditServiceServer) GetEntries(context.Context, *GetEntriesRequest) (*GetEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntries not implemented")
}
func (UnimplementedAuditServiceServer) GetEntry(context.Context, *GetEntryRequest) (*GetEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntry not implemented")
}
func (UnimplementedAuditServiceServer) GetDigest(context.Context, *GetDigestRequest) (*GetDigestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDigest not implemented")
}
func (UnimplementedAuditServiceServer) ExportCage(context.Context, *ExportCageRequest) (*ExportCageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportCage not implemented")
}
func (UnimplementedAuditServiceServer) ListCagesWithAudit(context.Context, *ListCagesWithAuditRequest) (*ListCagesWithAuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCagesWithAudit not implemented")
}
func (UnimplementedAuditServiceServer) GetKeyVersions(context.Context, *GetKeyVersionsRequest) (*GetKeyVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeyVersions not implemented")
}
func (UnimplementedAuditServiceServer) ChainStatus(context.Context, *ChainStatusRequest) (*ChainStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChainStatus not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}
func (UnimplementedAuditServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_VerifyChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).VerifyChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_VerifyChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).VerifyChain(ctx, req.(*VerifyChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetEntries(ctx, req.(*GetEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetEntry(ctx, req.(*GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetDigest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDigestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetDigest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetDigest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetDigest(ctx, req.(*GetDigestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ExportCage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportCageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ExportCage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ExportCage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ExportCage(ctx, req.(*ExportCageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ListCagesWithAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCagesWithAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ListCagesWithAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ListCagesWithAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ListCagesWithAudit(ctx, req.(*ListCagesWithAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetKeyVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetKeyVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetKeyVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetKeyVersions(ctx, req.(*GetKeyVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_ChainStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChainStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).ChainStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_ChainStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).ChainStatus(ctx, req.(*ChainStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentcage.audit.v1.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyChain",
			Handler:    _AuditService_VerifyChain_Handler,
		},
		{
			MethodName: "GetEntries",
			Handler:    _AuditService_GetEntries_Handler,
		},
		{
			MethodName: "GetEntry",
			Handler:    _AuditService_GetEntry_Handler,
		},
		{
			MethodName: "GetDigest",
			Handler:    _AuditService_GetDigest_Handler,
		},
		{
			MethodName: "ExportCage",
			Handler:    _AuditService_ExportCage_Handler,
		},
		{
			MethodName: "ListCagesWithAudit",
			Handler:    _AuditService_ListCagesWithAudit_Handler,
		},
		{
			MethodName: "GetKeyVersions",
			Handler:    _AuditService_GetKeyVersions_Handler,
		},
		{
			MethodName: "ChainStatus",
			Handler:    _AuditService_ChainStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/audit.proto",
}
