// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/audit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CageId        string                 `protobuf:"bytes,2,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	AssessmentId  string                 `protobuf:"bytes,3,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	Sequence      int64                  `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data          []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	KeyVersion    string                 `protobuf:"bytes,8,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	Signature     []byte                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	PreviousHash  []byte                 `protobuf:"bytes,10,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_api_proto_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

func (x *AuditEntry) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *AuditEntry) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AuditEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuditEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AuditEntry) GetKeyVersion() string {
	if x != nil {
		return x.KeyVersion
	}
	return ""
}

func (x *AuditEntry) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuditEntry) GetPreviousHash() []byte {
	if x != nil {
		return x.PreviousHash
	}
	return nil
}

type AuditDigest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	CageId        string                 `protobuf:"bytes,2,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	ChainHeadHash []byte                 `protobuf:"bytes,3,opt,name=chain_head_hash,json=chainHeadHash,proto3" json:"chain_head_hash,omitempty"`
	EntryCount    int64                  `protobuf:"varint,4,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	KeyVersion    string                 `protobuf:"bytes,5,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditDigest) Reset() {
	*x = AuditDigest{}
	mi := &file_api_proto_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditDigest) ProtoMessage() {}

func (x *AuditDigest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditDigest.ProtoReflect.Descriptor instead.
func (*AuditDigest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{1}
}

func (x *AuditDigest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *AuditDigest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

func (x *AuditDigest) GetChainHeadHash() []byte {
	if x != nil {
		return x.ChainHeadHash
	}
	return nil
}

func (x *AuditDigest) GetEntryCount() int64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *AuditDigest) GetKeyVersion() string {
	if x != nil {
		return x.KeyVersion
	}
	return ""
}

func (x *AuditDigest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuditDigest) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

type VerifyChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyChainRequest) Reset() {
	*x = VerifyChainRequest{}
	mi := &file_api_proto_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyChainRequest) ProtoMessage() {}

func (x *VerifyChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyChainRequest.ProtoReflect.Descriptor instead.
func (*VerifyChainRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyChainRequest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

type VerifyChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	EntryCount    int64                  `protobuf:"varint,3,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyChainResponse) Reset() {
	*x = VerifyChainResponse{}
	mi := &file_api_proto_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyChainResponse) ProtoMessage() {}

func (x *VerifyChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyChainResponse.ProtoReflect.Descriptor instead.
func (*VerifyChainResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyChainResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyChainResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *VerifyChainResponse) GetEntryCount() int64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

type GetEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	TypeFilter    string                 `protobuf:"bytes,2,opt,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntriesRequest) Reset() {
	*x = GetEntriesRequest{}
	mi := &file_api_proto_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntriesRequest) ProtoMessage() {}

func (x *GetEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntriesRequest.ProtoReflect.Descriptor instead.
func (*GetEntriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{4}
}

func (x *GetEntriesRequest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

func (x *GetEntriesRequest) GetTypeFilter() string {
	if x != nil {
		return x.TypeFilter
	}
	return ""
}

func (x *GetEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntriesResponse) Reset() {
	*x = GetEntriesResponse{}
	mi := &file_api_proto_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntriesResponse) ProtoMessage() {}

func (x *GetEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntriesResponse.ProtoReflect.Descriptor instead.
func (*GetEntriesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{5}
}

func (x *GetEntriesResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	mi := &file_api_proto_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryRequest.ProtoReflect.Descriptor instead.
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{6}
}

func (x *GetEntryRequest) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

type GetEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *AuditEntry            `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryResponse) Reset() {
	*x = GetEntryResponse{}
	mi := &file_api_proto_audit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryResponse) ProtoMessage() {}

func (x *GetEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryResponse.ProtoReflect.Descriptor instead.
func (*GetEntryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{7}
}

func (x *GetEntryResponse) GetEntry() *AuditEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type GetDigestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDigestRequest) Reset() {
	*x = GetDigestRequest{}
	mi := &file_api_proto_audit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDigestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigestRequest) ProtoMessage() {}

func (x *GetDigestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigestRequest.ProtoReflect.Descriptor instead.
func (*GetDigestRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{8}
}

func (x *GetDigestRequest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

type GetDigestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        *AuditDigest           `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDigestResponse) Reset() {
	*x = GetDigestResponse{}
	mi := &file_api_proto_audit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDigestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigestResponse) ProtoMessage() {}

func (x *GetDigestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigestResponse.ProtoReflect.Descriptor instead.
func (*GetDigestResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{9}
}

func (x *GetDigestResponse) GetDigest() *AuditDigest {
	if x != nil {
		return x.Digest
	}
	return nil
}

type ExportCageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportCageRequest) Reset() {
	*x = ExportCageRequest{}
	mi := &file_api_proto_audit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportCageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportCageRequest) ProtoMessage() {}

func (x *ExportCageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportCageRequest.ProtoReflect.Descriptor instead.
func (*ExportCageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{10}
}

func (x *ExportCageRequest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

type ExportCageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExportJson    []byte                 `protobuf:"bytes,1,opt,name=export_json,json=exportJson,proto3" json:"export_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportCageResponse) Reset() {
	*x = ExportCageResponse{}
	mi := &file_api_proto_audit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportCageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportCageResponse) ProtoMessage() {}

func (x *ExportCageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportCageResponse.ProtoReflect.Descriptor instead.
func (*ExportCageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{11}
}

func (x *ExportCageResponse) GetExportJson() []byte {
	if x != nil {
		return x.ExportJson
	}
	return nil
}

type ListCagesWithAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCagesWithAuditRequest) Reset() {
	*x = ListCagesWithAuditRequest{}
	mi := &file_api_proto_audit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCagesWithAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCagesWithAuditRequest) ProtoMessage() {}

func (x *ListCagesWithAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCagesWithAuditRequest.ProtoReflect.Descriptor instead.
func (*ListCagesWithAuditRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{12}
}

func (x *ListCagesWithAuditRequest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

type ListCagesWithAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageIds       []string               `protobuf:"bytes,1,rep,name=cage_ids,json=cageIds,proto3" json:"cage_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCagesWithAuditResponse) Reset() {
	*x = ListCagesWithAuditResponse{}
	mi := &file_api_proto_audit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCagesWithAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCagesWithAuditResponse) ProtoMessage() {}

func (x *ListCagesWithAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCagesWithAuditResponse.ProtoReflect.Descriptor instead.
func (*ListCagesWithAuditResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{13}
}

func (x *ListCagesWithAuditResponse) GetCageIds() []string {
	if x != nil {
		return x.CageIds
	}
	return nil
}

type GetKeyVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyVersionsRequest) Reset() {
	*x = GetKeyVersionsRequest{}
	mi := &file_api_proto_audit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyVersionsRequest) ProtoMessage() {}

func (x *GetKeyVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyVersionsRequest.ProtoReflect.Descriptor instead.
func (*GetKeyVersionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{14}
}

func (x *GetKeyVersionsRequest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

type GetKeyVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyVersions   []string               `protobuf:"bytes,1,rep,name=key_versions,json=keyVersions,proto3" json:"key_versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyVersionsResponse) Reset() {
	*x = GetKeyVersionsResponse{}
	mi := &file_api_proto_audit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyVersionsResponse) ProtoMessage() {}

func (x *GetKeyVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyVersionsResponse.ProtoReflect.Descriptor instead.
func (*GetKeyVersionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{15}
}

func (x *GetKeyVersionsResponse) GetKeyVersions() []string {
	if x != nil {
		return x.KeyVersions
	}
	return nil
}

type ChainStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainStatusRequest) Reset() {
	*x = ChainStatusRequest{}
	mi := &file_api_proto_audit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainStatusRequest) ProtoMessage() {}

func (x *ChainStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainStatusRequest.ProtoReflect.Descriptor instead.
func (*ChainStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{16}
}

func (x *ChainStatusRequest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

type ChainStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CageId          string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	AssessmentId    string                 `protobuf:"bytes,2,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	EntryCount      int64                  `protobuf:"varint,3,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	FirstTimestamp  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=first_timestamp,json=firstTimestamp,proto3" json:"first_timestamp,omitempty"`
	LatestTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=latest_timestamp,json=latestTimestamp,proto3" json:"latest_timestamp,omitempty"`
	HasDigest       bool                   `protobuf:"varint,6,opt,name=has_digest,json=hasDigest,proto3" json:"has_digest,omitempty"`
	KeyVersions     []string               `protobuf:"bytes,7,rep,name=key_versions,json=keyVersions,proto3" json:"key_versions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChainStatusResponse) Reset() {
	*x = ChainStatusResponse{}
	mi := &file_api_proto_audit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainStatusResponse) ProtoMessage() {}

func (x *ChainStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainStatusResponse.ProtoReflect.Descriptor instead.
func (*ChainStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_proto_rawDescGZIP(), []int{17}
}

func (x *ChainStatusResponse) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

func (x *ChainStatusResponse) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *ChainStatusResponse) GetEntryCount() int64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *ChainStatusResponse) GetFirstTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstTimestamp
	}
	return nil
}

func (x *ChainStatusResponse) GetLatestTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.LatestTimestamp
	}
	return nil
}

func (x *ChainStatusResponse) GetHasDigest() bool {
	if x != nil {
		return x.HasDigest
	}
	return false
}

func (x *ChainStatusResponse) GetKeyVersions() []string {
	if x != nil {
		return x.KeyVersions
	}
	return nil
}

var File_api_proto_audit_proto protoreflect.FileDescriptor

const file_api_proto_audit_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/audit.proto\x12\x12agentcage.audit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x02\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acage_id\x18\x02 \x01(\tR\x06cageId\x12#\n" +
	"\rassessment_id\x18\x03 \x01(\tR\fassessmentId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x03R\bsequence\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\x12\x1f\n" +
	"\vkey_version\x18\b \x01(\tR\n" +
	"keyVersion\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\x12#\n" +
	"\rprevious_hash\x18\n" +
	" \x01(\fR\fpreviousHash\"\x8c\x02\n" +
	"\vAuditDigest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\x12\x17\n" +
	"\acage_id\x18\x02 \x01(\tR\x06cageId\x12&\n" +
	"\x0fchain_head_hash\x18\x03 \x01(\fR\rchainHeadHash\x12\x1f\n" +
	"\ventry_count\x18\x04 \x01(\x03R\n" +
	"entryCount\x12\x1f\n" +
	"\vkey_version\x18\x05 \x01(\tR\n" +
	"keyVersion\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x127\n" +
	"\tissued_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\"-\n" +
	"\x12VerifyChainRequest\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\"b\n" +
	"\x13VerifyChainResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\ventry_count\x18\x03 \x01(\x03R\n" +
	"entryCount\"c\n" +
	"\x11GetEntriesRequest\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\x12\x1f\n" +
	"\vtype_filter\x18\x02 \x01(\tR\n" +
	"typeFilter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"N\n" +
	"\x12GetEntriesResponse\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.agentcage.audit.v1.AuditEntryR\aentries\",\n" +
	"\x0fGetEntryRequest\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\"H\n" +
	"\x10GetEntryResponse\x124\n" +
	"\x05entry\x18\x01 \x01(\v2\x1e.agentcage.audit.v1.AuditEntryR\x05entry\"+\n" +
	"\x10GetDigestRequest\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\"L\n" +
	"\x11GetDigestResponse\x127\n" +
	"\x06digest\x18\x01 \x01(\v2\x1f.agentcage.audit.v1.AuditDigestR\x06digest\",\n" +
	"\x11ExportCageRequest\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\"5\n" +
	"\x12ExportCageResponse\x12\x1f\n" +
	"\vexport_json\x18\x01 \x01(\fR\n" +
	"exportJson\"@\n" +
	"\x19ListCagesWithAuditRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\"7\n" +
	"\x1aListCagesWithAuditResponse\x12\x19\n" +
	"\bcage_ids\x18\x01 \x03(\tR\acageIds\"0\n" +
	"\x15GetKeyVersionsRequest\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\";\n" +
	"\x16GetKeyVersionsResponse\x12!\n" +
	"\fkey_versions\x18\x01 \x03(\tR\vkeyVersions\"-\n" +
	"\x12ChainStatusRequest\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\"\xc2\x02\n" +
	"\x13ChainStatusResponse\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\x12#\n" +
	"\rassessment_id\x18\x02 \x01(\tR\fassessmentId\x12\x1f\n" +
	"\ventry_count\x18\x03 \x01(\x03R\n" +
	"entryCount\x12C\n" +
	"\x0ffirst_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0efirstTimestamp\x12E\n" +
	"\x10latest_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0flatestTimestamp\x12\x1d\n" +
	"\n" +
	"has_digest\x18\x06 \x01(\bR\thasDigest\x12!\n" +
	"\fkey_versions\x18\a \x03(\tR\vkeyVersions2\x97\x06\n" +
	"\fAuditService\x12^\n" +
	"\vVerifyChain\x12&.agentcage.audit.v1.VerifyChainRequest\x1a'.agentcage.audit.v1.VerifyChainResponse\x12[\n" +
	"\n" +
	"GetEntries\x12%.agentcage.audit.v1.GetEntriesRequest\x1a&.agentcage.audit.v1.GetEntriesResponse\x12U\n" +
	"\bGetEntry\x12#.agentcage.audit.v1.GetEntryRequest\x1a$.agentcage.audit.v1.GetEntryResponse\x12X\n" +
	"\tGetDigest\x12$.agentcage.audit.v1.GetDigestRequest\x1a%.agentcage.audit.v1.GetDigestResponse\x12[\n" +
	"\n" +
	"ExportCage\x12%.agentcage.audit.v1.ExportCageRequest\x1a&.agentcage.audit.v1.ExportCageResponse\x12s\n" +
	"\x12ListCagesWithAudit\x12-.agentcage.audit.v1.ListCagesWithAuditRequest\x1a..agentcage.audit.v1.ListCagesWithAuditResponse\x12g\n" +
	"\x0eGetKeyVersions\x12).agentcage.audit.v1.GetKeyVersionsRequest\x1a*.agentcage.audit.v1.GetKeyVersionsResponse\x12^\n" +
	"\vChainStatus\x12&.agentcage.audit.v1.ChainStatusRequest\x1a'.agentcage.audit.v1.ChainStatusResponseB(Z&github.com/okedeji/agentcage/api/protob\x06proto3"

var (
	file_api_proto_audit_proto_rawDescOnce sync.Once
	file_api_proto_audit_proto_rawDescData []byte
)

func file_api_proto_audit_proto_rawDescGZIP() []byte {
	file_api_proto_audit_proto_rawDescOnce.Do(func() {
		file_api_proto_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_audit_proto_rawDesc), len(file_api_proto_audit_proto_rawDesc)))
	})
	return file_api_proto_audit_proto_rawDescData
}

var file_api_proto_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_audit_proto_goTypes = []any{
	(*AuditEntry)(nil),                 // 0: agentcage.audit.v1.AuditEntry
	(*AuditDigest)(nil),                // 1: agentcage.audit.v1.AuditDigest
	(*VerifyChainRequest)(nil),         // 2: agentcage.audit.v1.VerifyChainRequest
	(*VerifyChainResponse)(nil),        // 3: agentcage.audit.v1.VerifyChainResponse
	(*GetEntriesRequest)(nil),          // 4: agentcage.audit.v1.GetEntriesRequest
	(*GetEntriesResponse)(nil),         // 5: agentcage.audit.v1.GetEntriesResponse
	(*GetEntryRequest)(nil),            // 6: agentcage.audit.v1.GetEntryRequest
	(*GetEntryResponse)(nil),           // 7: agentcage.audit.v1.GetEntryResponse
	(*GetDigestRequest)(nil),           // 8: agentcage.audit.v1.GetDigestRequest
	(*GetDigestResponse)(nil),          // 9: agentcage.audit.v1.GetDigestResponse
	(*ExportCageRequest)(nil),          // 10: agentcage.audit.v1.ExportCageRequest
	(*ExportCageResponse)(nil),         // 11: agentcage.audit.v1.ExportCageResponse
	(*ListCagesWithAuditRequest)(nil),  // 12: agentcage.audit.v1.ListCagesWithAuditRequest
	(*ListCagesWithAuditResponse)(nil), // 13: agentcage.audit.v1.ListCagesWithAuditResponse
	(*GetKeyVersionsRequest)(nil),      // 14: agentcage.audit.v1.GetKeyVersionsRequest
	(*GetKeyVersionsResponse)(nil),     // 15: agentcage.audit.v1.GetKeyVersionsResponse
	(*ChainStatusRequest)(nil),         // 16: agentcage.audit.v1.ChainStatusRequest
	(*ChainStatusResponse)(nil),        // 17: agentcage.audit.v1.ChainStatusResponse
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
}
var file_api_proto_audit_proto_depIdxs = []int32{
	18, // 0: agentcage.audit.v1.AuditEntry.timestamp:type_name -> google.protobuf.Timestamp
	18, // 1: agentcage.audit.v1.AuditDigest.issued_at:type_name -> google.protobuf.Timestamp
	0,  // 2: agentcage.audit.v1.GetEntriesResponse.entries:type_name -> agentcage.audit.v1.AuditEntry
	0,  // 3: agentcage.audit.v1.GetEntryResponse.entry:type_name -> agentcage.audit.v1.AuditEntry
	1,  // 4: agentcage.audit.v1.GetDigestResponse.digest:type_name -> agentcage.audit.v1.AuditDigest
	18, // 5: agentcage.audit.v1.ChainStatusResponse.first_timestamp:type_name -> google.protobuf.Timestamp
	18, // 6: agentcage.audit.v1.ChainStatusResponse.latest_timestamp:type_name -> google.protobuf.Timestamp
	2,  // 7: agentcage.audit.v1.AuditService.VerifyChain:input_type -> agentcage.audit.v1.VerifyChainRequest
	4,  // 8: agentcage.audit.v1.AuditService.GetEntries:input_type -> agentcage.audit.v1.GetEntriesRequest
	6,  // 9: agentcage.audit.v1.AuditService.GetEntry:input_type -> agentcage.audit.v1.GetEntryRequest
	8,  // 10: agentcage.audit.v1.AuditService.GetDigest:input_type -> agentcage.audit.v1.GetDigestRequest
	10, // 11: agentcage.audit.v1.AuditService.ExportCage:input_type -> agentcage.audit.v1.ExportCageRequest
	12, // 12: agentcage.audit.v1.AuditService.ListCagesWithAudit:input_type -> agentcage.audit.v1.ListCagesWithAuditRequest
	14, // 13: agentcage.audit.v1.AuditService.GetKeyVersions:input_type -> agentcage.audit.v1.GetKeyVersionsRequest
	16, // 14: agentcage.audit.v1.AuditService.ChainStatus:input_type -> agentcage.audit.v1.ChainStatusRequest
	3,  // 15: agentcage.audit.v1.AuditService.VerifyChain:output_type -> agentcage.audit.v1.VerifyChainResponse
	5,  // 16: agentcage.audit.v1.AuditService.GetEntries:output_type -> agentcage.audit.v1.GetEntriesResponse
	7,  // 17: agentcage.audit.v1.AuditService.GetEntry:output_type -> agentcage.audit.v1.GetEntryResponse
	9,  // 18: agentcage.audit.v1.AuditService.GetDigest:output_type -> agentcage.audit.v1.GetDigestResponse
	11, // 19: agentcage.audit.v1.AuditService.ExportCage:output_type -> agentcage.audit.v1.ExportCageResponse
	13, // 20: agentcage.audit.v1.AuditService.ListCagesWithAudit:output_type -> agentcage.audit.v1.ListCagesWithAuditResponse
	15, // 21: agentcage.audit.v1.AuditService.GetKeyVersions:output_type -> agentcage.audit.v1.GetKeyVersionsResponse
	17, // 22: agentcage.audit.v1.AuditService.ChainStatus:output_type -> agentcage.audit.v1.ChainStatusResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_audit_proto_init() }
func file_api_proto_audit_proto_init() {
	if File_api_proto_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_audit_proto_rawDesc), len(file_api_proto_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_audit_proto_goTypes,
		DependencyIndexes: file_api_proto_audit_proto_depIdxs,
		MessageInfos:      file_api_proto_audit_proto_msgTypes,
	}.Build()
	File_api_proto_audit_proto = out.File
	file_api_proto_audit_proto_goTypes = nil
	file_api_proto_audit_proto_depIdxs = nil
}
