// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/cage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CageType int32

const (
	CageType_CAGE_TYPE_UNSPECIFIED CageType = 0
	CageType_CAGE_TYPE_DISCOVERY   CageType = 1
	CageType_CAGE_TYPE_VALIDATOR   CageType = 2
	CageType_CAGE_TYPE_ESCALATION  CageType = 3
)

// Enum value maps for CageType.
var (
	CageType_name = map[int32]string{
		0: "CAGE_TYPE_UNSPECIFIED",
		1: "CAGE_TYPE_DISCOVERY",
		2: "CAGE_TYPE_VALIDATOR",
		3: "CAGE_TYPE_ESCALATION",
	}
	CageType_value = map[string]int32{
		"CAGE_TYPE_UNSPECIFIED": 0,
		"CAGE_TYPE_DISCOVERY":   1,
		"CAGE_TYPE_VALIDATOR":   2,
		"CAGE_TYPE_ESCALATION":  3,
	}
)

func (x CageType) Enum() *CageType {
	p := new(CageType)
	*p = x
	return p
}

func (x CageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cage_proto_enumTypes[0].Descriptor()
}

func (CageType) Type() protoreflect.EnumType {
	return &file_api_proto_cage_proto_enumTypes[0]
}

func (x CageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CageType.Descriptor instead.
func (CageType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{0}
}

type CageState int32

const (
	CageState_CAGE_STATE_UNSPECIFIED  CageState = 0
	CageState_CAGE_STATE_PENDING      CageState = 1
	CageState_CAGE_STATE_PROVISIONING CageState = 2
	CageState_CAGE_STATE_RUNNING      CageState = 3
	CageState_CAGE_STATE_PAUSED       CageState = 4
	CageState_CAGE_STATE_TEARING_DOWN CageState = 5
	CageState_CAGE_STATE_COMPLETED    CageState = 6
	CageState_CAGE_STATE_FAILED       CageState = 7
)

// Enum value maps for CageState.
var (
	CageState_name = map[int32]string{
		0: "CAGE_STATE_UNSPECIFIED",
		1: "CAGE_STATE_PENDING",
		2: "CAGE_STATE_PROVISIONING",
		3: "CAGE_STATE_RUNNING",
		4: "CAGE_STATE_PAUSED",
		5: "CAGE_STATE_TEARING_DOWN",
		6: "CAGE_STATE_COMPLETED",
		7: "CAGE_STATE_FAILED",
	}
	CageState_value = map[string]int32{
		"CAGE_STATE_UNSPECIFIED":  0,
		"CAGE_STATE_PENDING":      1,
		"CAGE_STATE_PROVISIONING": 2,
		"CAGE_STATE_RUNNING":      3,
		"CAGE_STATE_PAUSED":       4,
		"CAGE_STATE_TEARING_DOWN": 5,
		"CAGE_STATE_COMPLETED":    6,
		"CAGE_STATE_FAILED":       7,
	}
)

func (x CageState) Enum() *CageState {
	p := new(CageState)
	*p = x
	return p
}

func (x CageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CageState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cage_proto_enumTypes[1].Descriptor()
}

func (CageState) Type() protoreflect.EnumType {
	return &file_api_proto_cage_proto_enumTypes[1]
}

func (x CageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CageState.Descriptor instead.
func (CageState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{1}
}

type PayloadProxyMode int32

const (
	PayloadProxyMode_PAYLOAD_PROXY_MODE_UNSPECIFIED PayloadProxyMode = 0
	PayloadProxyMode_PAYLOAD_PROXY_MODE_BLOCKLIST   PayloadProxyMode = 1
	PayloadProxyMode_PAYLOAD_PROXY_MODE_CLASSIFY    PayloadProxyMode = 2
	PayloadProxyMode_PAYLOAD_PROXY_MODE_DISABLED    PayloadProxyMode = 3
)

// Enum value maps for PayloadProxyMode.
var (
	PayloadProxyMode_name = map[int32]string{
		0: "PAYLOAD_PROXY_MODE_UNSPECIFIED",
		1: "PAYLOAD_PROXY_MODE_BLOCKLIST",
		2: "PAYLOAD_PROXY_MODE_CLASSIFY",
		3: "PAYLOAD_PROXY_MODE_DISABLED",
	}
	PayloadProxyMode_value = map[string]int32{
		"PAYLOAD_PROXY_MODE_UNSPECIFIED": 0,
		"PAYLOAD_PROXY_MODE_BLOCKLIST":   1,
		"PAYLOAD_PROXY_MODE_CLASSIFY":    2,
		"PAYLOAD_PROXY_MODE_DISABLED":    3,
	}
)

func (x PayloadProxyMode) Enum() *PayloadProxyMode {
	p := new(PayloadProxyMode)
	*p = x
	return p
}

func (x PayloadProxyMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadProxyMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cage_proto_enumTypes[2].Descriptor()
}

func (PayloadProxyMode) Type() protoreflect.EnumType {
	return &file_api_proto_cage_proto_enumTypes[2]
}

func (x PayloadProxyMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadProxyMode.Descriptor instead.
func (PayloadProxyMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{2}
}

type RoutingStrategy int32

const (
	RoutingStrategy_ROUTING_STRATEGY_UNSPECIFIED    RoutingStrategy = 0
	RoutingStrategy_ROUTING_STRATEGY_COST_OPTIMIZED RoutingStrategy = 1
	RoutingStrategy_ROUTING_STRATEGY_QUALITY_FIRST  RoutingStrategy = 2
	RoutingStrategy_ROUTING_STRATEGY_LATENCY_FIRST  RoutingStrategy = 3
)

// Enum value maps for RoutingStrategy.
var (
	RoutingStrategy_name = map[int32]string{
		0: "ROUTING_STRATEGY_UNSPECIFIED",
		1: "ROUTING_STRATEGY_COST_OPTIMIZED",
		2: "ROUTING_STRATEGY_QUALITY_FIRST",
		3: "ROUTING_STRATEGY_LATENCY_FIRST",
	}
	RoutingStrategy_value = map[string]int32{
		"ROUTING_STRATEGY_UNSPECIFIED":    0,
		"ROUTING_STRATEGY_COST_OPTIMIZED": 1,
		"ROUTING_STRATEGY_QUALITY_FIRST":  2,
		"ROUTING_STRATEGY_LATENCY_FIRST":  3,
	}
)

func (x RoutingStrategy) Enum() *RoutingStrategy {
	p := new(RoutingStrategy)
	*p = x
	return p
}

func (x RoutingStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutingStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_cage_proto_enumTypes[3].Descriptor()
}

func (RoutingStrategy) Type() protoreflect.EnumType {
	return &file_api_proto_cage_proto_enumTypes[3]
}

func (x RoutingStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutingStrategy.Descriptor instead.
func (RoutingStrategy) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{3}
}

type TargetScope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []string               `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Ports         []string               `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	Paths         []string               `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	Extras        []string               `protobuf:"bytes,4,rep,name=extras,proto3" json:"extras,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetScope) Reset() {
	*x = TargetScope{}
	mi := &file_api_proto_cage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetScope) ProtoMessage() {}

func (x *TargetScope) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetScope.ProtoReflect.Descriptor instead.
func (*TargetScope) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{0}
}

func (x *TargetScope) GetHosts() []string {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *TargetScope) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *TargetScope) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *TargetScope) GetExtras() []string {
	if x != nil {
		return x.Extras
	}
	return nil
}

type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vcpus         int32                  `protobuf:"varint,1,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_api_proto_cage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceLimits) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *ResourceLimits) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

type TimeLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxDuration   *durationpb.Duration   `protobuf:"bytes,1,opt,name=max_duration,json=maxDuration,proto3" json:"max_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeLimits) Reset() {
	*x = TimeLimits{}
	mi := &file_api_proto_cage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeLimits) ProtoMessage() {}

func (x *TimeLimits) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeLimits.ProtoReflect.Descriptor instead.
func (*TimeLimits) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{2}
}

func (x *TimeLimits) GetMaxDuration() *durationpb.Duration {
	if x != nil {
		return x.MaxDuration
	}
	return nil
}

type RateLimits struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerSecond int32                  `protobuf:"varint,1,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RateLimits) Reset() {
	*x = RateLimits{}
	mi := &file_api_proto_cage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimits) ProtoMessage() {}

func (x *RateLimits) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimits.ProtoReflect.Descriptor instead.
func (*RateLimits) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{3}
}

func (x *RateLimits) GetRequestsPerSecond() int32 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

type LLMGatewayConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TokenBudget     int64                  `protobuf:"varint,1,opt,name=token_budget,json=tokenBudget,proto3" json:"token_budget,omitempty"`
	RoutingStrategy RoutingStrategy        `protobuf:"varint,2,opt,name=routing_strategy,json=routingStrategy,proto3,enum=agentcage.cage.v1.RoutingStrategy" json:"routing_strategy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LLMGatewayConfig) Reset() {
	*x = LLMGatewayConfig{}
	mi := &file_api_proto_cage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMGatewayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMGatewayConfig) ProtoMessage() {}

func (x *LLMGatewayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMGatewayConfig.ProtoReflect.Descriptor instead.
func (*LLMGatewayConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{4}
}

func (x *LLMGatewayConfig) GetTokenBudget() int64 {
	if x != nil {
		return x.TokenBudget
	}
	return 0
}

func (x *LLMGatewayConfig) GetRoutingStrategy() RoutingStrategy {
	if x != nil {
		return x.RoutingStrategy
	}
	return RoutingStrategy_ROUTING_STRATEGY_UNSPECIFIED
}

type PayloadProxyConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mode              PayloadProxyMode       `protobuf:"varint,1,opt,name=mode,proto3,enum=agentcage.cage.v1.PayloadProxyMode" json:"mode,omitempty"`
	BlocklistPatterns []string               `protobuf:"bytes,2,rep,name=blocklist_patterns,json=blocklistPatterns,proto3" json:"blocklist_patterns,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PayloadProxyConfig) Reset() {
	*x = PayloadProxyConfig{}
	mi := &file_api_proto_cage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadProxyConfig) ProtoMessage() {}

func (x *PayloadProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadProxyConfig.ProtoReflect.Descriptor instead.
func (*PayloadProxyConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{5}
}

func (x *PayloadProxyConfig) GetMode() PayloadProxyMode {
	if x != nil {
		return x.Mode
	}
	return PayloadProxyMode_PAYLOAD_PROXY_MODE_UNSPECIFIED
}

func (x *PayloadProxyConfig) GetBlocklistPatterns() []string {
	if x != nil {
		return x.BlocklistPatterns
	}
	return nil
}

type CageConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId    string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	Type            CageType               `protobuf:"varint,2,opt,name=type,proto3,enum=agentcage.cage.v1.CageType" json:"type,omitempty"`
	Scope           *TargetScope           `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Resources       *ResourceLimits        `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	TimeLimits      *TimeLimits            `protobuf:"bytes,5,opt,name=time_limits,json=timeLimits,proto3" json:"time_limits,omitempty"`
	RateLimits      *RateLimits            `protobuf:"bytes,6,opt,name=rate_limits,json=rateLimits,proto3" json:"rate_limits,omitempty"`
	LlmGateway      *LLMGatewayConfig      `protobuf:"bytes,7,opt,name=llm_gateway,json=llmGateway,proto3,oneof" json:"llm_gateway,omitempty"`
	ProxyConfig     *PayloadProxyConfig    `protobuf:"bytes,8,opt,name=proxy_config,json=proxyConfig,proto3" json:"proxy_config,omitempty"`
	ParentFindingId string                 `protobuf:"bytes,9,opt,name=parent_finding_id,json=parentFindingId,proto3" json:"parent_finding_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CageConfig) Reset() {
	*x = CageConfig{}
	mi := &file_api_proto_cage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CageConfig) ProtoMessage() {}

func (x *CageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CageConfig.ProtoReflect.Descriptor instead.
func (*CageConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{6}
}

func (x *CageConfig) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *CageConfig) GetType() CageType {
	if x != nil {
		return x.Type
	}
	return CageType_CAGE_TYPE_UNSPECIFIED
}

func (x *CageConfig) GetScope() *TargetScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *CageConfig) GetResources() *ResourceLimits {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CageConfig) GetTimeLimits() *TimeLimits {
	if x != nil {
		return x.TimeLimits
	}
	return nil
}

func (x *CageConfig) GetRateLimits() *RateLimits {
	if x != nil {
		return x.RateLimits
	}
	return nil
}

func (x *CageConfig) GetLlmGateway() *LLMGatewayConfig {
	if x != nil {
		return x.LlmGateway
	}
	return nil
}

func (x *CageConfig) GetProxyConfig() *PayloadProxyConfig {
	if x != nil {
		return x.ProxyConfig
	}
	return nil
}

func (x *CageConfig) GetParentFindingId() string {
	if x != nil {
		return x.ParentFindingId
	}
	return ""
}

type CageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	AssessmentId  string                 `protobuf:"bytes,2,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	Type          CageType               `protobuf:"varint,3,opt,name=type,proto3,enum=agentcage.cage.v1.CageType" json:"type,omitempty"`
	State         CageState              `protobuf:"varint,4,opt,name=state,proto3,enum=agentcage.cage.v1.CageState" json:"state,omitempty"`
	Config        *CageConfig            `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CageInfo) Reset() {
	*x = CageInfo{}
	mi := &file_api_proto_cage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CageInfo) ProtoMessage() {}

func (x *CageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CageInfo.ProtoReflect.Descriptor instead.
func (*CageInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{7}
}

func (x *CageInfo) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

func (x *CageInfo) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *CageInfo) GetType() CageType {
	if x != nil {
		return x.Type
	}
	return CageType_CAGE_TYPE_UNSPECIFIED
}

func (x *CageInfo) GetState() CageState {
	if x != nil {
		return x.State
	}
	return CageState_CAGE_STATE_UNSPECIFIED
}

func (x *CageInfo) GetConfig() *CageConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CageInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CageInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *CageConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCageRequest) Reset() {
	*x = CreateCageRequest{}
	mi := &file_api_proto_cage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCageRequest) ProtoMessage() {}

func (x *CreateCageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCageRequest.ProtoReflect.Descriptor instead.
func (*CreateCageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCageRequest) GetConfig() *CageConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateCageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cage          *CageInfo              `protobuf:"bytes,1,opt,name=cage,proto3" json:"cage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCageResponse) Reset() {
	*x = CreateCageResponse{}
	mi := &file_api_proto_cage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCageResponse) ProtoMessage() {}

func (x *CreateCageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCageResponse.ProtoReflect.Descriptor instead.
func (*CreateCageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCageResponse) GetCage() *CageInfo {
	if x != nil {
		return x.Cage
	}
	return nil
}

type GetCageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCageRequest) Reset() {
	*x = GetCageRequest{}
	mi := &file_api_proto_cage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCageRequest) ProtoMessage() {}

func (x *GetCageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCageRequest.ProtoReflect.Descriptor instead.
func (*GetCageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{10}
}

func (x *GetCageRequest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

type GetCageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cage          *CageInfo              `protobuf:"bytes,1,opt,name=cage,proto3" json:"cage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCageResponse) Reset() {
	*x = GetCageResponse{}
	mi := &file_api_proto_cage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCageResponse) ProtoMessage() {}

func (x *GetCageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCageResponse.ProtoReflect.Descriptor instead.
func (*GetCageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{11}
}

func (x *GetCageResponse) GetCage() *CageInfo {
	if x != nil {
		return x.Cage
	}
	return nil
}

type DestroyCageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CageId        string                 `protobuf:"bytes,1,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyCageRequest) Reset() {
	*x = DestroyCageRequest{}
	mi := &file_api_proto_cage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyCageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyCageRequest) ProtoMessage() {}

func (x *DestroyCageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyCageRequest.ProtoReflect.Descriptor instead.
func (*DestroyCageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{12}
}

func (x *DestroyCageRequest) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

func (x *DestroyCageRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DestroyCageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyCageResponse) Reset() {
	*x = DestroyCageResponse{}
	mi := &file_api_proto_cage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyCageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyCageResponse) ProtoMessage() {}

func (x *DestroyCageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyCageResponse.ProtoReflect.Descriptor instead.
func (*DestroyCageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_cage_proto_rawDescGZIP(), []int{13}
}

var File_api_proto_cage_proto protoreflect.FileDescriptor

const file_api_proto_cage_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/cage.proto\x12\x11agentcage.cage.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n" +
	"\vTargetScope\x12\x14\n" +
	"\x05hosts\x18\x01 \x03(\tR\x05hosts\x12\x14\n" +
	"\x05ports\x18\x02 \x03(\tR\x05ports\x12\x14\n" +
	"\x05paths\x18\x03 \x03(\tR\x05paths\x12\x16\n" +
	"\x06extras\x18\x04 \x03(\tR\x06extras\"C\n" +
	"\x0eResourceLimits\x12\x14\n" +
	"\x05vcpus\x18\x01 \x01(\x05R\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x05R\bmemoryMb\"J\n" +
	"\n" +
	"TimeLimits\x12<\n" +
	"\fmax_duration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\vmaxDuration\"<\n" +
	"\n" +
	"RateLimits\x12.\n" +
	"\x13requests_per_second\x18\x01 \x01(\x05R\x11requestsPerSecond\"\x84\x01\n" +
	"\x10LLMGatewayConfig\x12!\n" +
	"\ftoken_budget\x18\x01 \x01(\x03R\vtokenBudget\x12M\n" +
	"\x10routing_strategy\x18\x02 \x01(\x0e2\".agentcage.cage.v1.RoutingStrategyR\x0froutingStrategy\"|\n" +
	"\x12PayloadProxyConfig\x127\n" +
	"\x04mode\x18\x01 \x01(\x0e2#.agentcage.cage.v1.PayloadProxyModeR\x04mode\x12-\n" +
	"\x12blocklist_patterns\x18\x02 \x03(\tR\x11blocklistPatterns\"\xaa\x04\n" +
	"\n" +
	"CageConfig\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.agentcage.cage.v1.CageTypeR\x04type\x124\n" +
	"\x05scope\x18\x03 \x01(\v2\x1e.agentcage.cage.v1.TargetScopeR\x05scope\x12?\n" +
	"\tresources\x18\x04 \x01(\v2!.agentcage.cage.v1.ResourceLimitsR\tresources\x12>\n" +
	"\vtime_limits\x18\x05 \x01(\v2\x1d.agentcage.cage.v1.TimeLimitsR\n" +
	"timeLimits\x12>\n" +
	"\vrate_limits\x18\x06 \x01(\v2\x1d.agentcage.cage.v1.RateLimitsR\n" +
	"rateLimits\x12I\n" +
	"\vllm_gateway\x18\a \x01(\v2#.agentcage.cage.v1.LLMGatewayConfigH\x00R\n" +
	"llmGateway\x88\x01\x01\x12H\n" +
	"\fproxy_config\x18\b \x01(\v2%.agentcage.cage.v1.PayloadProxyConfigR\vproxyConfig\x12*\n" +
	"\x11parent_finding_id\x18\t \x01(\tR\x0fparentFindingIdB\x0e\n" +
	"\f_llm_gateway\"\xda\x02\n" +
	"\bCageInfo\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\x12#\n" +
	"\rassessment_id\x18\x02 \x01(\tR\fassessmentId\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.agentcage.cage.v1.CageTypeR\x04type\x122\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1c.agentcage.cage.v1.CageStateR\x05state\x125\n" +
	"\x06config\x18\x05 \x01(\v2\x1d.agentcage.cage.v1.CageConfigR\x06config\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"J\n" +
	"\x11CreateCageRequest\x125\n" +
	"\x06config\x18\x01 \x01(\v2\x1d.agentcage.cage.v1.CageConfigR\x06config\"E\n" +
	"\x12CreateCageResponse\x12/\n" +
	"\x04cage\x18\x01 \x01(\v2\x1b.agentcage.cage.v1.CageInfoR\x04cage\")\n" +
	"\x0eGetCageRequest\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\"B\n" +
	"\x0fGetCageResponse\x12/\n" +
	"\x04cage\x18\x01 \x01(\v2\x1b.agentcage.cage.v1.CageInfoR\x04cage\"E\n" +
	"\x12DestroyCageRequest\x12\x17\n" +
	"\acage_id\x18\x01 \x01(\tR\x06cageId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x15\n" +
	"\x13DestroyCageResponse*q\n" +
	"\bCageType\x12\x19\n" +
	"\x15CAGE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CAGE_TYPE_DISCOVERY\x10\x01\x12\x17\n" +
	"\x13CAGE_TYPE_VALIDATOR\x10\x02\x12\x18\n" +
	"\x14CAGE_TYPE_ESCALATION\x10\x03*\xd9\x01\n" +
	"\tCageState\x12\x1a\n" +
	"\x16CAGE_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CAGE_STATE_PENDING\x10\x01\x12\x1b\n" +
	"\x17CAGE_STATE_PROVISIONING\x10\x02\x12\x16\n" +
	"\x12CAGE_STATE_RUNNING\x10\x03\x12\x15\n" +
	"\x11CAGE_STATE_PAUSED\x10\x04\x12\x1b\n" +
	"\x17CAGE_STATE_TEARING_DOWN\x10\x05\x12\x18\n" +
	"\x14CAGE_STATE_COMPLETED\x10\x06\x12\x15\n" +
	"\x11CAGE_STATE_FAILED\x10\a*\x9a\x01\n" +
	"\x10PayloadProxyMode\x12\"\n" +
	"\x1ePAYLOAD_PROXY_MODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPAYLOAD_PROXY_MODE_BLOCKLIST\x10\x01\x12\x1f\n" +
	"\x1bPAYLOAD_PROXY_MODE_CLASSIFY\x10\x02\x12\x1f\n" +
	"\x1bPAYLOAD_PROXY_MODE_DISABLED\x10\x03*\xa0\x01\n" +
	"\x0fRoutingStrategy\x12 \n" +
	"\x1cROUTING_STRATEGY_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fROUTING_STRATEGY_COST_OPTIMIZED\x10\x01\x12\"\n" +
	"\x1eROUTING_STRATEGY_QUALITY_FIRST\x10\x02\x12\"\n" +
	"\x1eROUTING_STRATEGY_LATENCY_FIRST\x10\x032\x98\x02\n" +
	"\vCageService\x12Y\n" +
	"\n" +
	"CreateCage\x12$.agentcage.cage.v1.CreateCageRequest\x1a%.agentcage.cage.v1.CreateCageResponse\x12P\n" +
	"\aGetCage\x12!.agentcage.cage.v1.GetCageRequest\x1a\".agentcage.cage.v1.GetCageResponse\x12\\\n" +
	"\vDestroyCage\x12%.agentcage.cage.v1.DestroyCageRequest\x1a&.agentcage.cage.v1.DestroyCageResponseB(Z&github.com/okedeji/agentcage/api/protob\x06proto3"

var (
	file_api_proto_cage_proto_rawDescOnce sync.Once
	file_api_proto_cage_proto_rawDescData []byte
)

func file_api_proto_cage_proto_rawDescGZIP() []byte {
	file_api_proto_cage_proto_rawDescOnce.Do(func() {
		file_api_proto_cage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cage_proto_rawDesc), len(file_api_proto_cage_proto_rawDesc)))
	})
	return file_api_proto_cage_proto_rawDescData
}

var file_api_proto_cage_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_proto_cage_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_cage_proto_goTypes = []any{
	(CageType)(0),                 // 0: agentcage.cage.v1.CageType
	(CageState)(0),                // 1: agentcage.cage.v1.CageState
	(PayloadProxyMode)(0),         // 2: agentcage.cage.v1.PayloadProxyMode
	(RoutingStrategy)(0),          // 3: agentcage.cage.v1.RoutingStrategy
	(*TargetScope)(nil),           // 4: agentcage.cage.v1.TargetScope
	(*ResourceLimits)(nil),        // 5: agentcage.cage.v1.ResourceLimits
	(*TimeLimits)(nil),            // 6: agentcage.cage.v1.TimeLimits
	(*RateLimits)(nil),            // 7: agentcage.cage.v1.RateLimits
	(*LLMGatewayConfig)(nil),      // 8: agentcage.cage.v1.LLMGatewayConfig
	(*PayloadProxyConfig)(nil),    // 9: agentcage.cage.v1.PayloadProxyConfig
	(*CageConfig)(nil),            // 10: agentcage.cage.v1.CageConfig
	(*CageInfo)(nil),              // 11: agentcage.cage.v1.CageInfo
	(*CreateCageRequest)(nil),     // 12: agentcage.cage.v1.CreateCageRequest
	(*CreateCageResponse)(nil),    // 13: agentcage.cage.v1.CreateCageResponse
	(*GetCageRequest)(nil),        // 14: agentcage.cage.v1.GetCageRequest
	(*GetCageResponse)(nil),       // 15: agentcage.cage.v1.GetCageResponse
	(*DestroyCageRequest)(nil),    // 16: agentcage.cage.v1.DestroyCageRequest
	(*DestroyCageResponse)(nil),   // 17: agentcage.cage.v1.DestroyCageResponse
	(*durationpb.Duration)(nil),   // 18: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_api_proto_cage_proto_depIdxs = []int32{
	18, // 0: agentcage.cage.v1.TimeLimits.max_duration:type_name -> google.protobuf.Duration
	3,  // 1: agentcage.cage.v1.LLMGatewayConfig.routing_strategy:type_name -> agentcage.cage.v1.RoutingStrategy
	2,  // 2: agentcage.cage.v1.PayloadProxyConfig.mode:type_name -> agentcage.cage.v1.PayloadProxyMode
	0,  // 3: agentcage.cage.v1.CageConfig.type:type_name -> agentcage.cage.v1.CageType
	4,  // 4: agentcage.cage.v1.CageConfig.scope:type_name -> agentcage.cage.v1.TargetScope
	5,  // 5: agentcage.cage.v1.CageConfig.resources:type_name -> agentcage.cage.v1.ResourceLimits
	6,  // 6: agentcage.cage.v1.CageConfig.time_limits:type_name -> agentcage.cage.v1.TimeLimits
	7,  // 7: agentcage.cage.v1.CageConfig.rate_limits:type_name -> agentcage.cage.v1.RateLimits
	8,  // 8: agentcage.cage.v1.CageConfig.llm_gateway:type_name -> agentcage.cage.v1.LLMGatewayConfig
	9,  // 9: agentcage.cage.v1.CageConfig.proxy_config:type_name -> agentcage.cage.v1.PayloadProxyConfig
	0,  // 10: agentcage.cage.v1.CageInfo.type:type_name -> agentcage.cage.v1.CageType
	1,  // 11: agentcage.cage.v1.CageInfo.state:type_name -> agentcage.cage.v1.CageState
	10, // 12: agentcage.cage.v1.CageInfo.config:type_name -> agentcage.cage.v1.CageConfig
	19, // 13: agentcage.cage.v1.CageInfo.created_at:type_name -> google.protobuf.Timestamp
	19, // 14: agentcage.cage.v1.CageInfo.updated_at:type_name -> google.protobuf.Timestamp
	10, // 15: agentcage.cage.v1.CreateCageRequest.config:type_name -> agentcage.cage.v1.CageConfig
	11, // 16: agentcage.cage.v1.CreateCageResponse.cage:type_name -> agentcage.cage.v1.CageInfo
	11, // 17: agentcage.cage.v1.GetCageResponse.cage:type_name -> agentcage.cage.v1.CageInfo
	12, // 18: agentcage.cage.v1.CageService.CreateCage:input_type -> agentcage.cage.v1.CreateCageRequest
	14, // 19: agentcage.cage.v1.CageService.GetCage:input_type -> agentcage.cage.v1.GetCageRequest
	16, // 20: agentcage.cage.v1.CageService.DestroyCage:input_type -> agentcage.cage.v1.DestroyCageRequest
	13, // 21: agentcage.cage.v1.CageService.CreateCage:output_type -> agentcage.cage.v1.CreateCageResponse
	15, // 22: agentcage.cage.v1.CageService.GetCage:output_type -> agentcage.cage.v1.GetCageResponse
	17, // 23: agentcage.cage.v1.CageService.DestroyCage:output_type -> agentcage.cage.v1.DestroyCageResponse
	21, // [21:24] is the sub-list for method output_type
	18, // [18:21] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_proto_cage_proto_init() }
func file_api_proto_cage_proto_init() {
	if File_api_proto_cage_proto != nil {
		return
	}
	file_api_proto_cage_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cage_proto_rawDesc), len(file_api_proto_cage_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cage_proto_goTypes,
		DependencyIndexes: file_api_proto_cage_proto_depIdxs,
		EnumInfos:         file_api_proto_cage_proto_enumTypes,
		MessageInfos:      file_api_proto_cage_proto_msgTypes,
	}.Build()
	File_api_proto_cage_proto = out.File
	file_api_proto_cage_proto_goTypes = nil
	file_api_proto_cage_proto_depIdxs = nil
}
