// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/cage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CageService_CreateCage_FullMethodName  = "/agentcage.cage.v1.CageService/CreateCage"
	CageService_GetCage_FullMethodName     = "/agentcage.cage.v1.CageService/GetCage"
	CageService_DestroyCage_FullMethodName = "/agentcage.cage.v1.CageService/DestroyCage"
)

// CageServiceClient is the client API for CageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CageServiceClient interface {
	CreateCage(ctx context.Context, in *CreateCageRequest, opts ...grpc.CallOption) (*CreateCageResponse, error)
	GetCage(ctx context.Context, in *GetCageRequest, opts ...grpc.CallOption) (*GetCageResponse, error)
	DestroyCage(ctx context.Context, in *DestroyCageRequest, opts ...grpc.CallOption) (*DestroyCageResponse, error)
}

type cageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCageServiceClient(cc grpc.ClientConnInterface) CageServiceClient {
	return &cageServiceClient{cc}
}

func (c *cageServiceClient) CreateCage(ctx context.Context, in *CreateCageRequest, opts ...grpc.CallOption) (*CreateCageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCageResponse)
	err := c.cc.Invoke(ctx, CageService_CreateCage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cageServiceClient) GetCage(ctx context.Context, in *GetCageRequest, opts ...grpc.CallOption) (*GetCageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCageResponse)
	err := c.cc.Invoke(ctx, CageService_GetCage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cageServiceClient) DestroyCage(ctx context.Context, in *DestroyCageRequest, opts ...grpc.CallOption) (*DestroyCageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyCageResponse)
	err := c.cc.Invoke(ctx, CageService_DestroyCage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CageServiceServer is the server API for CageService service.
// All implementations must embed UnimplementedCageServiceServer
// for forward compatibility.
type CageServiceServer interface {
	CreateCage(context.Context, *CreateCageRequest) (*CreateCageResponse, error)
	GetCage(context.Context, *GetCageRequest) (*GetCageResponse, error)
	DestroyCage(context.Context, *DestroyCageRequest) (*DestroyCageResponse, error)
	mustEmbedUnimplementedCageServiceServer()
}

// UnimplementedCageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCageServiceServer struct{}

func (UnimplementedCageServiceServer) CreateCage(context.Context, *CreateCageRequest) (*CreateCageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCage not implemented")
}
func (UnimplementedCageServiceServer) GetCage(context.Context, *GetCageRequest) (*GetCageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCage not implemented")
}
func (UnimplementedCageServiceServer) DestroyCage(context.Context, *DestroyCageRequest) (*DestroyCageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyCage not implemented")
}
func (UnimplementedCageServiceServer) mustEmbedUnimplementedCageServiceServer() {}
func (UnimplementedCageServiceServer) testEmbeddedByValue()                     {}

// UnsafeCageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CageServiceServer will
// result in compilation errors.
type UnsafeCageServiceServer interface {
	mustEmbedUnimplementedCageServiceServer()
}

func RegisterCageServiceServer(s grpc.ServiceRegistrar, srv CageServiceServer) {
	// If the following call panics, it indicates UnimplementedCageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CageService_ServiceDesc, srv)
}

func _CageService_CreateCage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CageServiceServer).CreateCage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CageService_CreateCage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CageServiceServer).CreateCage(ctx, req.(*CreateCageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CageService_GetCage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CageServiceServer).GetCage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CageService_GetCage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CageServiceServer).GetCage(ctx, req.(*GetCageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CageService_DestroyCage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyCageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CageServiceServer).DestroyCage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CageService_DestroyCage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CageServiceServer).DestroyCage(ctx, req.(*DestroyCageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CageService_ServiceDesc is the grpc.ServiceDesc for CageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentcage.cage.v1.CageService",
	HandlerType: (*CageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCage",
			Handler:    _CageService_CreateCage_Handler,
		},
		{
			MethodName: "GetCage",
			Handler:    _CageService_GetCage_Handler,
		},
		{
			MethodName: "DestroyCage",
			Handler:    _CageService_DestroyCage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/cage.proto",
}
