// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_api_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{2}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_api_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{3}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      map[string]string      `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetServices() map[string]string {
	if x != nil {
		return x.Services
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_api_proto_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{6}
}

type GetConfigResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConfigYaml       []byte                 `protobuf:"bytes,1,opt,name=config_yaml,json=configYaml,proto3" json:"config_yaml,omitempty"`
	CaCert           []byte                 `protobuf:"bytes,2,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	ServiceEndpoints *ServiceEndpoints      `protobuf:"bytes,3,opt,name=service_endpoints,json=serviceEndpoints,proto3" json:"service_endpoints,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_api_proto_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{7}
}

func (x *GetConfigResponse) GetConfigYaml() []byte {
	if x != nil {
		return x.ConfigYaml
	}
	return nil
}

func (x *GetConfigResponse) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *GetConfigResponse) GetServiceEndpoints() *ServiceEndpoints {
	if x != nil {
		return x.ServiceEndpoints
	}
	return nil
}

type ServiceEndpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpireServer   string                 `protobuf:"bytes,1,opt,name=spire_server,json=spireServer,proto3" json:"spire_server,omitempty"`
	NomadServer   string                 `protobuf:"bytes,2,opt,name=nomad_server,json=nomadServer,proto3" json:"nomad_server,omitempty"`
	RootfsUrl     string                 `protobuf:"bytes,3,opt,name=rootfs_url,json=rootfsUrl,proto3" json:"rootfs_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEndpoints) Reset() {
	*x = ServiceEndpoints{}
	mi := &file_api_proto_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEndpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEndpoints) ProtoMessage() {}

func (x *ServiceEndpoints) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEndpoints.ProtoReflect.Descriptor instead.
func (*ServiceEndpoints) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceEndpoints) GetSpireServer() string {
	if x != nil {
		return x.SpireServer
	}
	return ""
}

func (x *ServiceEndpoints) GetNomadServer() string {
	if x != nil {
		return x.NomadServer
	}
	return ""
}

func (x *ServiceEndpoints) GetRootfsUrl() string {
	if x != nil {
		return x.RootfsUrl
	}
	return ""
}

type GetServiceLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	TailLines     int32                  `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceLogRequest) Reset() {
	*x = GetServiceLogRequest{}
	mi := &file_api_proto_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceLogRequest) ProtoMessage() {}

func (x *GetServiceLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceLogRequest.ProtoReflect.Descriptor instead.
func (*GetServiceLogRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{9}
}

func (x *GetServiceLogRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetServiceLogRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

type GetServiceLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceLogResponse) Reset() {
	*x = GetServiceLogResponse{}
	mi := &file_api_proto_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceLogResponse) ProtoMessage() {}

func (x *GetServiceLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceLogResponse.ProtoReflect.Descriptor instead.
func (*GetServiceLogResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{10}
}

func (x *GetServiceLogResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

type StreamServiceLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	TailLines     int32                  `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamServiceLogRequest) Reset() {
	*x = StreamServiceLogRequest{}
	mi := &file_api_proto_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamServiceLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamServiceLogRequest) ProtoMessage() {}

func (x *StreamServiceLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamServiceLogRequest.ProtoReflect.Descriptor instead.
func (*StreamServiceLogRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{11}
}

func (x *StreamServiceLogRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *StreamServiceLogRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

type StreamServiceLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamServiceLogResponse) Reset() {
	*x = StreamServiceLogResponse{}
	mi := &file_api_proto_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamServiceLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamServiceLogResponse) ProtoMessage() {}

func (x *StreamServiceLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamServiceLogResponse.ProtoReflect.Descriptor instead.
func (*StreamServiceLogResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{12}
}

func (x *StreamServiceLogResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

var File_api_proto_control_proto protoreflect.FileDescriptor

const file_api_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/control.proto\x12\x14agentcage.control.v1\"\r\n" +
	"\vPingRequest\"@\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\r\n" +
	"\vStopRequest\"\x0e\n" +
	"\fStopResponse\"\x0f\n" +
	"\rHealthRequest\"\x9d\x01\n" +
	"\x0eHealthResponse\x12N\n" +
	"\bservices\x18\x01 \x03(\v22.agentcage.control.v1.HealthResponse.ServicesEntryR\bservices\x1a;\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x12\n" +
	"\x10GetConfigRequest\"\xa2\x01\n" +
	"\x11GetConfigResponse\x12\x1f\n" +
	"\vconfig_yaml\x18\x01 \x01(\fR\n" +
	"configYaml\x12\x17\n" +
	"\aca_cert\x18\x02 \x01(\fR\x06caCert\x12S\n" +
	"\x11service_endpoints\x18\x03 \x01(\v2&.agentcage.control.v1.ServiceEndpointsR\x10serviceEndpoints\"w\n" +
	"\x10ServiceEndpoints\x12!\n" +
	"\fspire_server\x18\x01 \x01(\tR\vspireServer\x12!\n" +
	"\fnomad_server\x18\x02 \x01(\tR\vnomadServer\x12\x1d\n" +
	"\n" +
	"rootfs_url\x18\x03 \x01(\tR\trootfsUrl\"O\n" +
	"\x14GetServiceLogRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x05R\ttailLines\"-\n" +
	"\x15GetServiceLogResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\"R\n" +
	"\x17StreamServiceLogRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x05R\ttailLines\".\n" +
	"\x18StreamServiceLogResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line2\xc0\x04\n" +
	"\x0eControlService\x12M\n" +
	"\x04Ping\x12!.agentcage.control.v1.PingRequest\x1a\".agentcage.control.v1.PingResponse\x12M\n" +
	"\x04Stop\x12!.agentcage.control.v1.StopRequest\x1a\".agentcage.control.v1.StopResponse\x12S\n" +
	"\x06Health\x12#.agentcage.control.v1.HealthRequest\x1a$.agentcage.control.v1.HealthResponse\x12\\\n" +
	"\tGetConfig\x12&.agentcage.control.v1.GetConfigRequest\x1a'.agentcage.control.v1.GetConfigResponse\x12h\n" +
	"\rGetServiceLog\x12*.agentcage.control.v1.GetServiceLogRequest\x1a+.agentcage.control.v1.GetServiceLogResponse\x12s\n" +
	"\x10StreamServiceLog\x12-.agentcage.control.v1.StreamServiceLogRequest\x1a..agentcage.control.v1.StreamServiceLogResponse0\x01B(Z&github.com/okedeji/agentcage/api/protob\x06proto3"

var (
	file_api_proto_control_proto_rawDescOnce sync.Once
	file_api_proto_control_proto_rawDescData []byte
)

func file_api_proto_control_proto_rawDescGZIP() []byte {
	file_api_proto_control_proto_rawDescOnce.Do(func() {
		file_api_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_control_proto_rawDesc), len(file_api_proto_control_proto_rawDesc)))
	})
	return file_api_proto_control_proto_rawDescData
}

var file_api_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_control_proto_goTypes = []any{
	(*PingRequest)(nil),              // 0: agentcage.control.v1.PingRequest
	(*PingResponse)(nil),             // 1: agentcage.control.v1.PingResponse
	(*StopRequest)(nil),              // 2: agentcage.control.v1.StopRequest
	(*StopResponse)(nil),             // 3: agentcage.control.v1.StopResponse
	(*HealthRequest)(nil),            // 4: agentcage.control.v1.HealthRequest
	(*HealthResponse)(nil),           // 5: agentcage.control.v1.HealthResponse
	(*GetConfigRequest)(nil),         // 6: agentcage.control.v1.GetConfigRequest
	(*GetConfigResponse)(nil),        // 7: agentcage.control.v1.GetConfigResponse
	(*ServiceEndpoints)(nil),         // 8: agentcage.control.v1.ServiceEndpoints
	(*GetServiceLogRequest)(nil),     // 9: agentcage.control.v1.GetServiceLogRequest
	(*GetServiceLogResponse)(nil),    // 10: agentcage.control.v1.GetServiceLogResponse
	(*StreamServiceLogRequest)(nil),  // 11: agentcage.control.v1.StreamServiceLogRequest
	(*StreamServiceLogResponse)(nil), // 12: agentcage.control.v1.StreamServiceLogResponse
	nil,                              // 13: agentcage.control.v1.HealthResponse.ServicesEntry
}
var file_api_proto_control_proto_depIdxs = []int32{
	13, // 0: agentcage.control.v1.HealthResponse.services:type_name -> agentcage.control.v1.HealthResponse.ServicesEntry
	8,  // 1: agentcage.control.v1.GetConfigResponse.service_endpoints:type_name -> agentcage.control.v1.ServiceEndpoints
	0,  // 2: agentcage.control.v1.ControlService.Ping:input_type -> agentcage.control.v1.PingRequest
	2,  // 3: agentcage.control.v1.ControlService.Stop:input_type -> agentcage.control.v1.StopRequest
	4,  // 4: agentcage.control.v1.ControlService.Health:input_type -> agentcage.control.v1.HealthRequest
	6,  // 5: agentcage.control.v1.ControlService.GetConfig:input_type -> agentcage.control.v1.GetConfigRequest
	9,  // 6: agentcage.control.v1.ControlService.GetServiceLog:input_type -> agentcage.control.v1.GetServiceLogRequest
	11, // 7: agentcage.control.v1.ControlService.StreamServiceLog:input_type -> agentcage.control.v1.StreamServiceLogRequest
	1,  // 8: agentcage.control.v1.ControlService.Ping:output_type -> agentcage.control.v1.PingResponse
	3,  // 9: agentcage.control.v1.ControlService.Stop:output_type -> agentcage.control.v1.StopResponse
	5,  // 10: agentcage.control.v1.ControlService.Health:output_type -> agentcage.control.v1.HealthResponse
	7,  // 11: agentcage.control.v1.ControlService.GetConfig:output_type -> agentcage.control.v1.GetConfigResponse
	10, // 12: agentcage.control.v1.ControlService.GetServiceLog:output_type -> agentcage.control.v1.GetServiceLogResponse
	12, // 13: agentcage.control.v1.ControlService.StreamServiceLog:output_type -> agentcage.control.v1.StreamServiceLogResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_control_proto_init() }
func file_api_proto_control_proto_init() {
	if File_api_proto_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_control_proto_rawDesc), len(file_api_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_control_proto_goTypes,
		DependencyIndexes: file_api_proto_control_proto_depIdxs,
		MessageInfos:      file_api_proto_control_proto_msgTypes,
	}.Build()
	File_api_proto_control_proto = out.File
	file_api_proto_control_proto_goTypes = nil
	file_api_proto_control_proto_depIdxs = nil
}
