// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_api_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{2}
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_api_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{3}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      map[string]string      `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_control_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetServices() map[string]string {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_api_proto_control_proto protoreflect.FileDescriptor

const file_api_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/control.proto\x12\x14agentcage.control.v1\"\r\n" +
	"\vPingRequest\"@\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\r\n" +
	"\vStopRequest\"\x0e\n" +
	"\fStopResponse\"\x0f\n" +
	"\rHealthRequest\"\x9d\x01\n" +
	"\x0eHealthResponse\x12N\n" +
	"\bservices\x18\x01 \x03(\v22.agentcage.control.v1.HealthResponse.ServicesEntryR\bservices\x1a;\n" +
	"\rServicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x83\x02\n" +
	"\x0eControlService\x12M\n" +
	"\x04Ping\x12!.agentcage.control.v1.PingRequest\x1a\".agentcage.control.v1.PingResponse\x12M\n" +
	"\x04Stop\x12!.agentcage.control.v1.StopRequest\x1a\".agentcage.control.v1.StopResponse\x12S\n" +
	"\x06Health\x12#.agentcage.control.v1.HealthRequest\x1a$.agentcage.control.v1.HealthResponseB(Z&github.com/okedeji/agentcage/api/protob\x06proto3"

var (
	file_api_proto_control_proto_rawDescOnce sync.Once
	file_api_proto_control_proto_rawDescData []byte
)

func file_api_proto_control_proto_rawDescGZIP() []byte {
	file_api_proto_control_proto_rawDescOnce.Do(func() {
		file_api_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_control_proto_rawDesc), len(file_api_proto_control_proto_rawDesc)))
	})
	return file_api_proto_control_proto_rawDescData
}

var file_api_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_control_proto_goTypes = []any{
	(*PingRequest)(nil),    // 0: agentcage.control.v1.PingRequest
	(*PingResponse)(nil),   // 1: agentcage.control.v1.PingResponse
	(*StopRequest)(nil),    // 2: agentcage.control.v1.StopRequest
	(*StopResponse)(nil),   // 3: agentcage.control.v1.StopResponse
	(*HealthRequest)(nil),  // 4: agentcage.control.v1.HealthRequest
	(*HealthResponse)(nil), // 5: agentcage.control.v1.HealthResponse
	nil,                    // 6: agentcage.control.v1.HealthResponse.ServicesEntry
}
var file_api_proto_control_proto_depIdxs = []int32{
	6, // 0: agentcage.control.v1.HealthResponse.services:type_name -> agentcage.control.v1.HealthResponse.ServicesEntry
	0, // 1: agentcage.control.v1.ControlService.Ping:input_type -> agentcage.control.v1.PingRequest
	2, // 2: agentcage.control.v1.ControlService.Stop:input_type -> agentcage.control.v1.StopRequest
	4, // 3: agentcage.control.v1.ControlService.Health:input_type -> agentcage.control.v1.HealthRequest
	1, // 4: agentcage.control.v1.ControlService.Ping:output_type -> agentcage.control.v1.PingResponse
	3, // 5: agentcage.control.v1.ControlService.Stop:output_type -> agentcage.control.v1.StopResponse
	5, // 6: agentcage.control.v1.ControlService.Health:output_type -> agentcage.control.v1.HealthResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_control_proto_init() }
func file_api_proto_control_proto_init() {
	if File_api_proto_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_control_proto_rawDesc), len(file_api_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_control_proto_goTypes,
		DependencyIndexes: file_api_proto_control_proto_depIdxs,
		MessageInfos:      file_api_proto_control_proto_msgTypes,
	}.Build()
	File_api_proto_control_proto = out.File
	file_api_proto_control_proto_goTypes = nil
	file_api_proto_control_proto_depIdxs = nil
}
