// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/findings.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindingStatus int32

const (
	FindingStatus_FINDING_STATUS_UNSPECIFIED FindingStatus = 0
	FindingStatus_FINDING_STATUS_CANDIDATE   FindingStatus = 1
	FindingStatus_FINDING_STATUS_VALIDATED   FindingStatus = 2
	FindingStatus_FINDING_STATUS_REJECTED    FindingStatus = 3
)

// Enum value maps for FindingStatus.
var (
	FindingStatus_name = map[int32]string{
		0: "FINDING_STATUS_UNSPECIFIED",
		1: "FINDING_STATUS_CANDIDATE",
		2: "FINDING_STATUS_VALIDATED",
		3: "FINDING_STATUS_REJECTED",
	}
	FindingStatus_value = map[string]int32{
		"FINDING_STATUS_UNSPECIFIED": 0,
		"FINDING_STATUS_CANDIDATE":   1,
		"FINDING_STATUS_VALIDATED":   2,
		"FINDING_STATUS_REJECTED":    3,
	}
)

func (x FindingStatus) Enum() *FindingStatus {
	p := new(FindingStatus)
	*p = x
	return p
}

func (x FindingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_findings_proto_enumTypes[0].Descriptor()
}

func (FindingStatus) Type() protoreflect.EnumType {
	return &file_api_proto_findings_proto_enumTypes[0]
}

func (x FindingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingStatus.Descriptor instead.
func (FindingStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{0}
}

type FindingSeverity int32

const (
	FindingSeverity_FINDING_SEVERITY_UNSPECIFIED FindingSeverity = 0
	FindingSeverity_FINDING_SEVERITY_INFO        FindingSeverity = 1
	FindingSeverity_FINDING_SEVERITY_LOW         FindingSeverity = 2
	FindingSeverity_FINDING_SEVERITY_MEDIUM      FindingSeverity = 3
	FindingSeverity_FINDING_SEVERITY_HIGH        FindingSeverity = 4
	FindingSeverity_FINDING_SEVERITY_CRITICAL    FindingSeverity = 5
)

// Enum value maps for FindingSeverity.
var (
	FindingSeverity_name = map[int32]string{
		0: "FINDING_SEVERITY_UNSPECIFIED",
		1: "FINDING_SEVERITY_INFO",
		2: "FINDING_SEVERITY_LOW",
		3: "FINDING_SEVERITY_MEDIUM",
		4: "FINDING_SEVERITY_HIGH",
		5: "FINDING_SEVERITY_CRITICAL",
	}
	FindingSeverity_value = map[string]int32{
		"FINDING_SEVERITY_UNSPECIFIED": 0,
		"FINDING_SEVERITY_INFO":        1,
		"FINDING_SEVERITY_LOW":         2,
		"FINDING_SEVERITY_MEDIUM":      3,
		"FINDING_SEVERITY_HIGH":        4,
		"FINDING_SEVERITY_CRITICAL":    5,
	}
)

func (x FindingSeverity) Enum() *FindingSeverity {
	p := new(FindingSeverity)
	*p = x
	return p
}

func (x FindingSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindingSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_findings_proto_enumTypes[1].Descriptor()
}

func (FindingSeverity) Type() protoreflect.EnumType {
	return &file_api_proto_findings_proto_enumTypes[1]
}

func (x FindingSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FindingSeverity.Descriptor instead.
func (FindingSeverity) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{1}
}

type FindingEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       []byte                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response      []byte                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Screenshot    []byte                 `protobuf:"bytes,3,opt,name=screenshot,proto3" json:"screenshot,omitempty"`
	Poc           string                 `protobuf:"bytes,4,opt,name=poc,proto3" json:"poc,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingEvidence) Reset() {
	*x = FindingEvidence{}
	mi := &file_api_proto_findings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingEvidence) ProtoMessage() {}

func (x *FindingEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_findings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingEvidence.ProtoReflect.Descriptor instead.
func (*FindingEvidence) Descriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{0}
}

func (x *FindingEvidence) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FindingEvidence) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FindingEvidence) GetScreenshot() []byte {
	if x != nil {
		return x.Screenshot
	}
	return nil
}

func (x *FindingEvidence) GetPoc() string {
	if x != nil {
		return x.Poc
	}
	return ""
}

func (x *FindingEvidence) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ValidationProof struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReproductionSteps string                 `protobuf:"bytes,1,opt,name=reproduction_steps,json=reproductionSteps,proto3" json:"reproduction_steps,omitempty"`
	Confirmed         bool                   `protobuf:"varint,2,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Deterministic     bool                   `protobuf:"varint,3,opt,name=deterministic,proto3" json:"deterministic,omitempty"`
	ValidatorCageId   string                 `protobuf:"bytes,4,opt,name=validator_cage_id,json=validatorCageId,proto3" json:"validator_cage_id,omitempty"`
	Evidence          string                 `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ValidationProof) Reset() {
	*x = ValidationProof{}
	mi := &file_api_proto_findings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationProof) ProtoMessage() {}

func (x *ValidationProof) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_findings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationProof.ProtoReflect.Descriptor instead.
func (*ValidationProof) Descriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationProof) GetReproductionSteps() string {
	if x != nil {
		return x.ReproductionSteps
	}
	return ""
}

func (x *ValidationProof) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *ValidationProof) GetDeterministic() bool {
	if x != nil {
		return x.Deterministic
	}
	return false
}

func (x *ValidationProof) GetValidatorCageId() string {
	if x != nil {
		return x.ValidatorCageId
	}
	return ""
}

func (x *ValidationProof) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

type FindingInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FindingId       string                 `protobuf:"bytes,1,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	AssessmentId    string                 `protobuf:"bytes,2,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	CageId          string                 `protobuf:"bytes,3,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	Status          FindingStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=agentcage.findings.v1.FindingStatus" json:"status,omitempty"`
	Severity        FindingSeverity        `protobuf:"varint,5,opt,name=severity,proto3,enum=agentcage.findings.v1.FindingSeverity" json:"severity,omitempty"`
	Title           string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	VulnClass       string                 `protobuf:"bytes,8,opt,name=vuln_class,json=vulnClass,proto3" json:"vuln_class,omitempty"`
	Endpoint        string                 `protobuf:"bytes,9,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Evidence        *FindingEvidence       `protobuf:"bytes,10,opt,name=evidence,proto3" json:"evidence,omitempty"`
	ParentFindingId string                 `protobuf:"bytes,11,opt,name=parent_finding_id,json=parentFindingId,proto3" json:"parent_finding_id,omitempty"`
	ChainDepth      int32                  `protobuf:"varint,12,opt,name=chain_depth,json=chainDepth,proto3" json:"chain_depth,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ValidatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=validated_at,json=validatedAt,proto3" json:"validated_at,omitempty"`
	Cwe             string                 `protobuf:"bytes,15,opt,name=cwe,proto3" json:"cwe,omitempty"`
	CvssScore       float64                `protobuf:"fixed64,16,opt,name=cvss_score,json=cvssScore,proto3" json:"cvss_score,omitempty"`
	Remediation     string                 `protobuf:"bytes,17,opt,name=remediation,proto3" json:"remediation,omitempty"`
	ValidationProof *ValidationProof       `protobuf:"bytes,18,opt,name=validation_proof,json=validationProof,proto3" json:"validation_proof,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FindingInfo) Reset() {
	*x = FindingInfo{}
	mi := &file_api_proto_findings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingInfo) ProtoMessage() {}

func (x *FindingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_findings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingInfo.ProtoReflect.Descriptor instead.
func (*FindingInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{2}
}

func (x *FindingInfo) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *FindingInfo) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *FindingInfo) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

func (x *FindingInfo) GetStatus() FindingStatus {
	if x != nil {
		return x.Status
	}
	return FindingStatus_FINDING_STATUS_UNSPECIFIED
}

func (x *FindingInfo) GetSeverity() FindingSeverity {
	if x != nil {
		return x.Severity
	}
	return FindingSeverity_FINDING_SEVERITY_UNSPECIFIED
}

func (x *FindingInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FindingInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FindingInfo) GetVulnClass() string {
	if x != nil {
		return x.VulnClass
	}
	return ""
}

func (x *FindingInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *FindingInfo) GetEvidence() *FindingEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *FindingInfo) GetParentFindingId() string {
	if x != nil {
		return x.ParentFindingId
	}
	return ""
}

func (x *FindingInfo) GetChainDepth() int32 {
	if x != nil {
		return x.ChainDepth
	}
	return 0
}

func (x *FindingInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FindingInfo) GetValidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidatedAt
	}
	return nil
}

func (x *FindingInfo) GetCwe() string {
	if x != nil {
		return x.Cwe
	}
	return ""
}

func (x *FindingInfo) GetCvssScore() float64 {
	if x != nil {
		return x.CvssScore
	}
	return 0
}

func (x *FindingInfo) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

func (x *FindingInfo) GetValidationProof() *ValidationProof {
	if x != nil {
		return x.ValidationProof
	}
	return nil
}

type ListFindingsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId   string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	StatusFilter   FindingStatus          `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=agentcage.findings.v1.FindingStatus" json:"status_filter,omitempty"`
	SeverityFilter FindingSeverity        `protobuf:"varint,3,opt,name=severity_filter,json=severityFilter,proto3,enum=agentcage.findings.v1.FindingSeverity" json:"severity_filter,omitempty"`
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListFindingsRequest) Reset() {
	*x = ListFindingsRequest{}
	mi := &file_api_proto_findings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFindingsRequest) ProtoMessage() {}

func (x *ListFindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_findings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFindingsRequest.ProtoReflect.Descriptor instead.
func (*ListFindingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{3}
}

func (x *ListFindingsRequest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *ListFindingsRequest) GetStatusFilter() FindingStatus {
	if x != nil {
		return x.StatusFilter
	}
	return FindingStatus_FINDING_STATUS_UNSPECIFIED
}

func (x *ListFindingsRequest) GetSeverityFilter() FindingSeverity {
	if x != nil {
		return x.SeverityFilter
	}
	return FindingSeverity_FINDING_SEVERITY_UNSPECIFIED
}

func (x *ListFindingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListFindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Findings      []*FindingInfo         `protobuf:"bytes,1,rep,name=findings,proto3" json:"findings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFindingsResponse) Reset() {
	*x = ListFindingsResponse{}
	mi := &file_api_proto_findings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFindingsResponse) ProtoMessage() {}

func (x *ListFindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_findings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFindingsResponse.ProtoReflect.Descriptor instead.
func (*ListFindingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{4}
}

func (x *ListFindingsResponse) GetFindings() []*FindingInfo {
	if x != nil {
		return x.Findings
	}
	return nil
}

type GetFindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FindingId     string                 `protobuf:"bytes,1,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFindingRequest) Reset() {
	*x = GetFindingRequest{}
	mi := &file_api_proto_findings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFindingRequest) ProtoMessage() {}

func (x *GetFindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_findings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFindingRequest.ProtoReflect.Descriptor instead.
func (*GetFindingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{5}
}

func (x *GetFindingRequest) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

type GetFindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finding       *FindingInfo           `protobuf:"bytes,1,opt,name=finding,proto3" json:"finding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFindingResponse) Reset() {
	*x = GetFindingResponse{}
	mi := &file_api_proto_findings_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFindingResponse) ProtoMessage() {}

func (x *GetFindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_findings_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFindingResponse.ProtoReflect.Descriptor instead.
func (*GetFindingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{6}
}

func (x *GetFindingResponse) GetFinding() *FindingInfo {
	if x != nil {
		return x.Finding
	}
	return nil
}

type DeleteFindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FindingId     string                 `protobuf:"bytes,1,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFindingRequest) Reset() {
	*x = DeleteFindingRequest{}
	mi := &file_api_proto_findings_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFindingRequest) ProtoMessage() {}

func (x *DeleteFindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_findings_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFindingRequest.ProtoReflect.Descriptor instead.
func (*DeleteFindingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFindingRequest) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

type DeleteFindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFindingResponse) Reset() {
	*x = DeleteFindingResponse{}
	mi := &file_api_proto_findings_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFindingResponse) ProtoMessage() {}

func (x *DeleteFindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_findings_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFindingResponse.ProtoReflect.Descriptor instead.
func (*DeleteFindingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{8}
}

type DeleteByAssessmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssessmentId  string                 `protobuf:"bytes,1,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByAssessmentRequest) Reset() {
	*x = DeleteByAssessmentRequest{}
	mi := &file_api_proto_findings_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByAssessmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByAssessmentRequest) ProtoMessage() {}

func (x *DeleteByAssessmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_findings_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByAssessmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteByAssessmentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteByAssessmentRequest) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

type DeleteByAssessmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int64                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByAssessmentResponse) Reset() {
	*x = DeleteByAssessmentResponse{}
	mi := &file_api_proto_findings_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByAssessmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByAssessmentResponse) ProtoMessage() {}

func (x *DeleteByAssessmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_findings_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByAssessmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteByAssessmentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_findings_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteByAssessmentResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_api_proto_findings_proto protoreflect.FileDescriptor

const file_api_proto_findings_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/findings.proto\x12\x15agentcage.findings.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x02\n" +
	"\x0fFindingEvidence\x12\x18\n" +
	"\arequest\x18\x01 \x01(\fR\arequest\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\fR\bresponse\x12\x1e\n" +
	"\n" +
	"screenshot\x18\x03 \x01(\fR\n" +
	"screenshot\x12\x10\n" +
	"\x03poc\x18\x04 \x01(\tR\x03poc\x12P\n" +
	"\bmetadata\x18\x05 \x03(\v24.agentcage.findings.v1.FindingEvidence.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x01\n" +
	"\x0fValidationProof\x12-\n" +
	"\x12reproduction_steps\x18\x01 \x01(\tR\x11reproductionSteps\x12\x1c\n" +
	"\tconfirmed\x18\x02 \x01(\bR\tconfirmed\x12$\n" +
	"\rdeterministic\x18\x03 \x01(\bR\rdeterministic\x12*\n" +
	"\x11validator_cage_id\x18\x04 \x01(\tR\x0fvalidatorCageId\x12\x1a\n" +
	"\bevidence\x18\x05 \x01(\tR\bevidence\"\x90\x06\n" +
	"\vFindingInfo\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x01 \x01(\tR\tfindingId\x12#\n" +
	"\rassessment_id\x18\x02 \x01(\tR\fassessmentId\x12\x17\n" +
	"\acage_id\x18\x03 \x01(\tR\x06cageId\x12<\n" +
	"\x06status\x18\x04 \x01(\x0e2$.agentcage.findings.v1.FindingStatusR\x06status\x12B\n" +
	"\bseverity\x18\x05 \x01(\x0e2&.agentcage.findings.v1.FindingSeverityR\bseverity\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"vuln_class\x18\b \x01(\tR\tvulnClass\x12\x1a\n" +
	"\bendpoint\x18\t \x01(\tR\bendpoint\x12B\n" +
	"\bevidence\x18\n" +
	" \x01(\v2&.agentcage.findings.v1.FindingEvidenceR\bevidence\x12*\n" +
	"\x11parent_finding_id\x18\v \x01(\tR\x0fparentFindingId\x12\x1f\n" +
	"\vchain_depth\x18\f \x01(\x05R\n" +
	"chainDepth\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fvalidated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vvalidatedAt\x12\x10\n" +
	"\x03cwe\x18\x0f \x01(\tR\x03cwe\x12\x1d\n" +
	"\n" +
	"cvss_score\x18\x10 \x01(\x01R\tcvssScore\x12 \n" +
	"\vremediation\x18\x11 \x01(\tR\vremediation\x12Q\n" +
	"\x10validation_proof\x18\x12 \x01(\v2&.agentcage.findings.v1.ValidationProofR\x0fvalidationProof\"\xec\x01\n" +
	"\x13ListFindingsRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\x12I\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2$.agentcage.findings.v1.FindingStatusR\fstatusFilter\x12O\n" +
	"\x0fseverity_filter\x18\x03 \x01(\x0e2&.agentcage.findings.v1.FindingSeverityR\x0eseverityFilter\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"V\n" +
	"\x14ListFindingsResponse\x12>\n" +
	"\bfindings\x18\x01 \x03(\v2\".agentcage.findings.v1.FindingInfoR\bfindings\"2\n" +
	"\x11GetFindingRequest\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x01 \x01(\tR\tfindingId\"R\n" +
	"\x12GetFindingResponse\x12<\n" +
	"\afinding\x18\x01 \x01(\v2\".agentcage.findings.v1.FindingInfoR\afinding\"5\n" +
	"\x14DeleteFindingRequest\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x01 \x01(\tR\tfindingId\"\x17\n" +
	"\x15DeleteFindingResponse\"@\n" +
	"\x19DeleteByAssessmentRequest\x12#\n" +
	"\rassessment_id\x18\x01 \x01(\tR\fassessmentId\"6\n" +
	"\x1aDeleteByAssessmentResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted*\x88\x01\n" +
	"\rFindingStatus\x12\x1e\n" +
	"\x1aFINDING_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18FINDING_STATUS_CANDIDATE\x10\x01\x12\x1c\n" +
	"\x18FINDING_STATUS_VALIDATED\x10\x02\x12\x1b\n" +
	"\x17FINDING_STATUS_REJECTED\x10\x03*\xbf\x01\n" +
	"\x0fFindingSeverity\x12 \n" +
	"\x1cFINDING_SEVERITY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FINDING_SEVERITY_INFO\x10\x01\x12\x18\n" +
	"\x14FINDING_SEVERITY_LOW\x10\x02\x12\x1b\n" +
	"\x17FINDING_SEVERITY_MEDIUM\x10\x03\x12\x19\n" +
	"\x15FINDING_SEVERITY_HIGH\x10\x04\x12\x1d\n" +
	"\x19FINDING_SEVERITY_CRITICAL\x10\x052\xc4\x03\n" +
	"\x0fFindingsService\x12g\n" +
	"\fListFindings\x12*.agentcage.findings.v1.ListFindingsRequest\x1a+.agentcage.findings.v1.ListFindingsResponse\x12a\n" +
	"\n" +
	"GetFinding\x12(.agentcage.findings.v1.GetFindingRequest\x1a).agentcage.findings.v1.GetFindingResponse\x12j\n" +
	"\rDeleteFinding\x12+.agentcage.findings.v1.DeleteFindingRequest\x1a,.agentcage.findings.v1.DeleteFindingResponse\x12y\n" +
	"\x12DeleteByAssessment\x120.agentcage.findings.v1.DeleteByAssessmentRequest\x1a1.agentcage.findings.v1.DeleteByAssessmentResponseB(Z&github.com/okedeji/agentcage/api/protob\x06proto3"

var (
	file_api_proto_findings_proto_rawDescOnce sync.Once
	file_api_proto_findings_proto_rawDescData []byte
)

func file_api_proto_findings_proto_rawDescGZIP() []byte {
	file_api_proto_findings_proto_rawDescOnce.Do(func() {
		file_api_proto_findings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_findings_proto_rawDesc), len(file_api_proto_findings_proto_rawDesc)))
	})
	return file_api_proto_findings_proto_rawDescData
}

var file_api_proto_findings_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_findings_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_findings_proto_goTypes = []any{
	(FindingStatus)(0),                 // 0: agentcage.findings.v1.FindingStatus
	(FindingSeverity)(0),               // 1: agentcage.findings.v1.FindingSeverity
	(*FindingEvidence)(nil),            // 2: agentcage.findings.v1.FindingEvidence
	(*ValidationProof)(nil),            // 3: agentcage.findings.v1.ValidationProof
	(*FindingInfo)(nil),                // 4: agentcage.findings.v1.FindingInfo
	(*ListFindingsRequest)(nil),        // 5: agentcage.findings.v1.ListFindingsRequest
	(*ListFindingsResponse)(nil),       // 6: agentcage.findings.v1.ListFindingsResponse
	(*GetFindingRequest)(nil),          // 7: agentcage.findings.v1.GetFindingRequest
	(*GetFindingResponse)(nil),         // 8: agentcage.findings.v1.GetFindingResponse
	(*DeleteFindingRequest)(nil),       // 9: agentcage.findings.v1.DeleteFindingRequest
	(*DeleteFindingResponse)(nil),      // 10: agentcage.findings.v1.DeleteFindingResponse
	(*DeleteByAssessmentRequest)(nil),  // 11: agentcage.findings.v1.DeleteByAssessmentRequest
	(*DeleteByAssessmentResponse)(nil), // 12: agentcage.findings.v1.DeleteByAssessmentResponse
	nil,                                // 13: agentcage.findings.v1.FindingEvidence.MetadataEntry
	(*timestamppb.Timestamp)(nil),      // 14: google.protobuf.Timestamp
}
var file_api_proto_findings_proto_depIdxs = []int32{
	13, // 0: agentcage.findings.v1.FindingEvidence.metadata:type_name -> agentcage.findings.v1.FindingEvidence.MetadataEntry
	0,  // 1: agentcage.findings.v1.FindingInfo.status:type_name -> agentcage.findings.v1.FindingStatus
	1,  // 2: agentcage.findings.v1.FindingInfo.severity:type_name -> agentcage.findings.v1.FindingSeverity
	2,  // 3: agentcage.findings.v1.FindingInfo.evidence:type_name -> agentcage.findings.v1.FindingEvidence
	14, // 4: agentcage.findings.v1.FindingInfo.created_at:type_name -> google.protobuf.Timestamp
	14, // 5: agentcage.findings.v1.FindingInfo.validated_at:type_name -> google.protobuf.Timestamp
	3,  // 6: agentcage.findings.v1.FindingInfo.validation_proof:type_name -> agentcage.findings.v1.ValidationProof
	0,  // 7: agentcage.findings.v1.ListFindingsRequest.status_filter:type_name -> agentcage.findings.v1.FindingStatus
	1,  // 8: agentcage.findings.v1.ListFindingsRequest.severity_filter:type_name -> agentcage.findings.v1.FindingSeverity
	4,  // 9: agentcage.findings.v1.ListFindingsResponse.findings:type_name -> agentcage.findings.v1.FindingInfo
	4,  // 10: agentcage.findings.v1.GetFindingResponse.finding:type_name -> agentcage.findings.v1.FindingInfo
	5,  // 11: agentcage.findings.v1.FindingsService.ListFindings:input_type -> agentcage.findings.v1.ListFindingsRequest
	7,  // 12: agentcage.findings.v1.FindingsService.GetFinding:input_type -> agentcage.findings.v1.GetFindingRequest
	9,  // 13: agentcage.findings.v1.FindingsService.DeleteFinding:input_type -> agentcage.findings.v1.DeleteFindingRequest
	11, // 14: agentcage.findings.v1.FindingsService.DeleteByAssessment:input_type -> agentcage.findings.v1.DeleteByAssessmentRequest
	6,  // 15: agentcage.findings.v1.FindingsService.ListFindings:output_type -> agentcage.findings.v1.ListFindingsResponse
	8,  // 16: agentcage.findings.v1.FindingsService.GetFinding:output_type -> agentcage.findings.v1.GetFindingResponse
	10, // 17: agentcage.findings.v1.FindingsService.DeleteFinding:output_type -> agentcage.findings.v1.DeleteFindingResponse
	12, // 18: agentcage.findings.v1.FindingsService.DeleteByAssessment:output_type -> agentcage.findings.v1.DeleteByAssessmentResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_findings_proto_init() }
func file_api_proto_findings_proto_init() {
	if File_api_proto_findings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_findings_proto_rawDesc), len(file_api_proto_findings_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_findings_proto_goTypes,
		DependencyIndexes: file_api_proto_findings_proto_depIdxs,
		EnumInfos:         file_api_proto_findings_proto_enumTypes,
		MessageInfos:      file_api_proto_findings_proto_msgTypes,
	}.Build()
	File_api_proto_findings_proto = out.File
	file_api_proto_findings_proto_goTypes = nil
	file_api_proto_findings_proto_depIdxs = nil
}
