// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/findings.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FindingsService_ListFindings_FullMethodName       = "/agentcage.findings.v1.FindingsService/ListFindings"
	FindingsService_GetFinding_FullMethodName         = "/agentcage.findings.v1.FindingsService/GetFinding"
	FindingsService_DeleteFinding_FullMethodName      = "/agentcage.findings.v1.FindingsService/DeleteFinding"
	FindingsService_DeleteByAssessment_FullMethodName = "/agentcage.findings.v1.FindingsService/DeleteByAssessment"
)

// FindingsServiceClient is the client API for FindingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FindingsServiceClient interface {
	ListFindings(ctx context.Context, in *ListFindingsRequest, opts ...grpc.CallOption) (*ListFindingsResponse, error)
	GetFinding(ctx context.Context, in *GetFindingRequest, opts ...grpc.CallOption) (*GetFindingResponse, error)
	DeleteFinding(ctx context.Context, in *DeleteFindingRequest, opts ...grpc.CallOption) (*DeleteFindingResponse, error)
	DeleteByAssessment(ctx context.Context, in *DeleteByAssessmentRequest, opts ...grpc.CallOption) (*DeleteByAssessmentResponse, error)
}

type findingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFindingsServiceClient(cc grpc.ClientConnInterface) FindingsServiceClient {
	return &findingsServiceClient{cc}
}

func (c *findingsServiceClient) ListFindings(ctx context.Context, in *ListFindingsRequest, opts ...grpc.CallOption) (*ListFindingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFindingsResponse)
	err := c.cc.Invoke(ctx, FindingsService_ListFindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *findingsServiceClient) GetFinding(ctx context.Context, in *GetFindingRequest, opts ...grpc.CallOption) (*GetFindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFindingResponse)
	err := c.cc.Invoke(ctx, FindingsService_GetFinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *findingsServiceClient) DeleteFinding(ctx context.Context, in *DeleteFindingRequest, opts ...grpc.CallOption) (*DeleteFindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFindingResponse)
	err := c.cc.Invoke(ctx, FindingsService_DeleteFinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *findingsServiceClient) DeleteByAssessment(ctx context.Context, in *DeleteByAssessmentRequest, opts ...grpc.CallOption) (*DeleteByAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteByAssessmentResponse)
	err := c.cc.Invoke(ctx, FindingsService_DeleteByAssessment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindingsServiceServer is the server API for FindingsService service.
// All implementations must embed UnimplementedFindingsServiceServer
// for forward compatibility.
type FindingsServiceServer interface {
	ListFindings(context.Context, *ListFindingsRequest) (*ListFindingsResponse, error)
	GetFinding(context.Context, *GetFindingRequest) (*GetFindingResponse, error)
	DeleteFinding(context.Context, *DeleteFindingRequest) (*DeleteFindingResponse, error)
	DeleteByAssessment(context.Context, *DeleteByAssessmentRequest) (*DeleteByAssessmentResponse, error)
	mustEmbedUnimplementedFindingsServiceServer()
}

// UnimplementedFindingsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFindingsServiceServer struct{}

func (UnimplementedFindingsServiceServer) ListFindings(context.Context, *ListFindingsRequest) (*ListFindingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFindings not implemented")
}
func (UnimplementedFindingsServiceServer) GetFinding(context.Context, *GetFindingRequest) (*GetFindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFinding not implemented")
}
func (UnimplementedFindingsServiceServer) DeleteFinding(context.Context, *DeleteFindingRequest) (*DeleteFindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFinding not implemented")
}
func (UnimplementedFindingsServiceServer) DeleteByAssessment(context.Context, *DeleteByAssessmentRequest) (*DeleteByAssessmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteByAssessment not implemented")
}
func (UnimplementedFindingsServiceServer) mustEmbedUnimplementedFindingsServiceServer() {}
func (UnimplementedFindingsServiceServer) testEmbeddedByValue()                         {}

// UnsafeFindingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FindingsServiceServer will
// result in compilation errors.
type UnsafeFindingsServiceServer interface {
	mustEmbedUnimplementedFindingsServiceServer()
}

func RegisterFindingsServiceServer(s grpc.ServiceRegistrar, srv FindingsServiceServer) {
	// If the following call panics, it indicates UnimplementedFindingsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FindingsService_ServiceDesc, srv)
}

func _FindingsService_ListFindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindingsServiceServer).ListFindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FindingsService_ListFindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindingsServiceServer).ListFindings(ctx, req.(*ListFindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FindingsService_GetFinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindingsServiceServer).GetFinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FindingsService_GetFinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindingsServiceServer).GetFinding(ctx, req.(*GetFindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FindingsService_DeleteFinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindingsServiceServer).DeleteFinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FindingsService_DeleteFinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindingsServiceServer).DeleteFinding(ctx, req.(*DeleteFindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FindingsService_DeleteByAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindingsServiceServer).DeleteByAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FindingsService_DeleteByAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindingsServiceServer).DeleteByAssessment(ctx, req.(*DeleteByAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FindingsService_ServiceDesc is the grpc.ServiceDesc for FindingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FindingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentcage.findings.v1.FindingsService",
	HandlerType: (*FindingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFindings",
			Handler:    _FindingsService_ListFindings_Handler,
		},
		{
			MethodName: "GetFinding",
			Handler:    _FindingsService_GetFinding_Handler,
		},
		{
			MethodName: "DeleteFinding",
			Handler:    _FindingsService_DeleteFinding_Handler,
		},
		{
			MethodName: "DeleteByAssessment",
			Handler:    _FindingsService_DeleteByAssessment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/findings.proto",
}
