// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/fleet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostPool int32

const (
	HostPool_HOST_POOL_UNSPECIFIED  HostPool = 0
	HostPool_HOST_POOL_ACTIVE       HostPool = 1
	HostPool_HOST_POOL_WARM         HostPool = 2
	HostPool_HOST_POOL_PROVISIONING HostPool = 3
	HostPool_HOST_POOL_DRAINING     HostPool = 4
)

// Enum value maps for HostPool.
var (
	HostPool_name = map[int32]string{
		0: "HOST_POOL_UNSPECIFIED",
		1: "HOST_POOL_ACTIVE",
		2: "HOST_POOL_WARM",
		3: "HOST_POOL_PROVISIONING",
		4: "HOST_POOL_DRAINING",
	}
	HostPool_value = map[string]int32{
		"HOST_POOL_UNSPECIFIED":  0,
		"HOST_POOL_ACTIVE":       1,
		"HOST_POOL_WARM":         2,
		"HOST_POOL_PROVISIONING": 3,
		"HOST_POOL_DRAINING":     4,
	}
)

func (x HostPool) Enum() *HostPool {
	p := new(HostPool)
	*p = x
	return p
}

func (x HostPool) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostPool) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_fleet_proto_enumTypes[0].Descriptor()
}

func (HostPool) Type() protoreflect.EnumType {
	return &file_api_proto_fleet_proto_enumTypes[0]
}

func (x HostPool) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostPool.Descriptor instead.
func (HostPool) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{0}
}

type HostState int32

const (
	HostState_HOST_STATE_UNSPECIFIED  HostState = 0
	HostState_HOST_STATE_INITIALIZING HostState = 1
	HostState_HOST_STATE_READY        HostState = 2
	HostState_HOST_STATE_BUSY         HostState = 3
	HostState_HOST_STATE_DRAINING     HostState = 4
	HostState_HOST_STATE_OFFLINE      HostState = 5
)

// Enum value maps for HostState.
var (
	HostState_name = map[int32]string{
		0: "HOST_STATE_UNSPECIFIED",
		1: "HOST_STATE_INITIALIZING",
		2: "HOST_STATE_READY",
		3: "HOST_STATE_BUSY",
		4: "HOST_STATE_DRAINING",
		5: "HOST_STATE_OFFLINE",
	}
	HostState_value = map[string]int32{
		"HOST_STATE_UNSPECIFIED":  0,
		"HOST_STATE_INITIALIZING": 1,
		"HOST_STATE_READY":        2,
		"HOST_STATE_BUSY":         3,
		"HOST_STATE_DRAINING":     4,
		"HOST_STATE_OFFLINE":      5,
	}
)

func (x HostState) Enum() *HostState {
	p := new(HostState)
	*p = x
	return p
}

func (x HostState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_fleet_proto_enumTypes[1].Descriptor()
}

func (HostState) Type() protoreflect.EnumType {
	return &file_api_proto_fleet_proto_enumTypes[1]
}

func (x HostState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostState.Descriptor instead.
func (HostState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{1}
}

type PoolStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pool           HostPool               `protobuf:"varint,1,opt,name=pool,proto3,enum=agentcage.fleet.v1.HostPool" json:"pool,omitempty"`
	HostCount      int32                  `protobuf:"varint,2,opt,name=host_count,json=hostCount,proto3" json:"host_count,omitempty"`
	CageSlotsTotal int32                  `protobuf:"varint,3,opt,name=cage_slots_total,json=cageSlotsTotal,proto3" json:"cage_slots_total,omitempty"`
	CageSlotsUsed  int32                  `protobuf:"varint,4,opt,name=cage_slots_used,json=cageSlotsUsed,proto3" json:"cage_slots_used,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PoolStatus) Reset() {
	*x = PoolStatus{}
	mi := &file_api_proto_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolStatus) ProtoMessage() {}

func (x *PoolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolStatus.ProtoReflect.Descriptor instead.
func (*PoolStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *PoolStatus) GetPool() HostPool {
	if x != nil {
		return x.Pool
	}
	return HostPool_HOST_POOL_UNSPECIFIED
}

func (x *PoolStatus) GetHostCount() int32 {
	if x != nil {
		return x.HostCount
	}
	return 0
}

func (x *PoolStatus) GetCageSlotsTotal() int32 {
	if x != nil {
		return x.CageSlotsTotal
	}
	return 0
}

func (x *PoolStatus) GetCageSlotsUsed() int32 {
	if x != nil {
		return x.CageSlotsUsed
	}
	return 0
}

type HostInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostId         string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Pool           HostPool               `protobuf:"varint,2,opt,name=pool,proto3,enum=agentcage.fleet.v1.HostPool" json:"pool,omitempty"`
	State          HostState              `protobuf:"varint,3,opt,name=state,proto3,enum=agentcage.fleet.v1.HostState" json:"state,omitempty"`
	CageSlotsTotal int32                  `protobuf:"varint,4,opt,name=cage_slots_total,json=cageSlotsTotal,proto3" json:"cage_slots_total,omitempty"`
	CageSlotsUsed  int32                  `protobuf:"varint,5,opt,name=cage_slots_used,json=cageSlotsUsed,proto3" json:"cage_slots_used,omitempty"`
	VcpusTotal     int32                  `protobuf:"varint,6,opt,name=vcpus_total,json=vcpusTotal,proto3" json:"vcpus_total,omitempty"`
	VcpusUsed      int32                  `protobuf:"varint,7,opt,name=vcpus_used,json=vcpusUsed,proto3" json:"vcpus_used,omitempty"`
	MemoryMbTotal  int32                  `protobuf:"varint,8,opt,name=memory_mb_total,json=memoryMbTotal,proto3" json:"memory_mb_total,omitempty"`
	MemoryMbUsed   int32                  `protobuf:"varint,9,opt,name=memory_mb_used,json=memoryMbUsed,proto3" json:"memory_mb_used,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_api_proto_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *HostInfo) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HostInfo) GetPool() HostPool {
	if x != nil {
		return x.Pool
	}
	return HostPool_HOST_POOL_UNSPECIFIED
}

func (x *HostInfo) GetState() HostState {
	if x != nil {
		return x.State
	}
	return HostState_HOST_STATE_UNSPECIFIED
}

func (x *HostInfo) GetCageSlotsTotal() int32 {
	if x != nil {
		return x.CageSlotsTotal
	}
	return 0
}

func (x *HostInfo) GetCageSlotsUsed() int32 {
	if x != nil {
		return x.CageSlotsUsed
	}
	return 0
}

func (x *HostInfo) GetVcpusTotal() int32 {
	if x != nil {
		return x.VcpusTotal
	}
	return 0
}

func (x *HostInfo) GetVcpusUsed() int32 {
	if x != nil {
		return x.VcpusUsed
	}
	return 0
}

func (x *HostInfo) GetMemoryMbTotal() int32 {
	if x != nil {
		return x.MemoryMbTotal
	}
	return 0
}

func (x *HostInfo) GetMemoryMbUsed() int32 {
	if x != nil {
		return x.MemoryMbUsed
	}
	return 0
}

type FleetStatus struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TotalHosts               int32                  `protobuf:"varint,1,opt,name=total_hosts,json=totalHosts,proto3" json:"total_hosts,omitempty"`
	Pools                    []*PoolStatus          `protobuf:"bytes,2,rep,name=pools,proto3" json:"pools,omitempty"`
	CapacityUtilizationRatio float32                `protobuf:"fixed32,3,opt,name=capacity_utilization_ratio,json=capacityUtilizationRatio,proto3" json:"capacity_utilization_ratio,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *FleetStatus) Reset() {
	*x = FleetStatus{}
	mi := &file_api_proto_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetStatus) ProtoMessage() {}

func (x *FleetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetStatus.ProtoReflect.Descriptor instead.
func (*FleetStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *FleetStatus) GetTotalHosts() int32 {
	if x != nil {
		return x.TotalHosts
	}
	return 0
}

func (x *FleetStatus) GetPools() []*PoolStatus {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *FleetStatus) GetCapacityUtilizationRatio() float32 {
	if x != nil {
		return x.CapacityUtilizationRatio
	}
	return 0
}

type GetFleetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFleetStatusRequest) Reset() {
	*x = GetFleetStatusRequest{}
	mi := &file_api_proto_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetStatusRequest) ProtoMessage() {}

func (x *GetFleetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetFleetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{3}
}

type GetFleetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *FleetStatus           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFleetStatusResponse) Reset() {
	*x = GetFleetStatusResponse{}
	mi := &file_api_proto_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetStatusResponse) ProtoMessage() {}

func (x *GetFleetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetFleetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *GetFleetStatusResponse) GetStatus() *FleetStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DrainHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainHostRequest) Reset() {
	*x = DrainHostRequest{}
	mi := &file_api_proto_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainHostRequest) ProtoMessage() {}

func (x *DrainHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainHostRequest.ProtoReflect.Descriptor instead.
func (*DrainHostRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *DrainHostRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *DrainHostRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DrainHostRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type DrainHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainHostResponse) Reset() {
	*x = DrainHostResponse{}
	mi := &file_api_proto_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainHostResponse) ProtoMessage() {}

func (x *DrainHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainHostResponse.ProtoReflect.Descriptor instead.
func (*DrainHostResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{6}
}

type ListHostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolFilter    HostPool               `protobuf:"varint,1,opt,name=pool_filter,json=poolFilter,proto3,enum=agentcage.fleet.v1.HostPool" json:"pool_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsRequest) Reset() {
	*x = ListHostsRequest{}
	mi := &file_api_proto_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsRequest) ProtoMessage() {}

func (x *ListHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsRequest.ProtoReflect.Descriptor instead.
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *ListHostsRequest) GetPoolFilter() HostPool {
	if x != nil {
		return x.PoolFilter
	}
	return HostPool_HOST_POOL_UNSPECIFIED
}

type ListHostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*HostInfo            `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsResponse) Reset() {
	*x = ListHostsResponse{}
	mi := &file_api_proto_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsResponse) ProtoMessage() {}

func (x *ListHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsResponse.ProtoReflect.Descriptor instead.
func (*ListHostsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *ListHostsResponse) GetHosts() []*HostInfo {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type GetCapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapacityRequest) Reset() {
	*x = GetCapacityRequest{}
	mi := &file_api_proto_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityRequest) ProtoMessage() {}

func (x *GetCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityRequest.ProtoReflect.Descriptor instead.
func (*GetCapacityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{9}
}

type GetCapacityResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Pools              []*PoolStatus          `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
	AvailableCageSlots int32                  `protobuf:"varint,2,opt,name=available_cage_slots,json=availableCageSlots,proto3" json:"available_cage_slots,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetCapacityResponse) Reset() {
	*x = GetCapacityResponse{}
	mi := &file_api_proto_fleet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapacityResponse) ProtoMessage() {}

func (x *GetCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapacityResponse.ProtoReflect.Descriptor instead.
func (*GetCapacityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_proto_rawDescGZIP(), []int{10}
}

func (x *GetCapacityResponse) GetPools() []*PoolStatus {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *GetCapacityResponse) GetAvailableCageSlots() int32 {
	if x != nil {
		return x.AvailableCageSlots
	}
	return 0
}

var File_api_proto_fleet_proto protoreflect.FileDescriptor

const file_api_proto_fleet_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/fleet.proto\x12\x12agentcage.fleet.v1\"\xaf\x01\n" +
	"\n" +
	"PoolStatus\x120\n" +
	"\x04pool\x18\x01 \x01(\x0e2\x1c.agentcage.fleet.v1.HostPoolR\x04pool\x12\x1d\n" +
	"\n" +
	"host_count\x18\x02 \x01(\x05R\thostCount\x12(\n" +
	"\x10cage_slots_total\x18\x03 \x01(\x05R\x0ecageSlotsTotal\x12&\n" +
	"\x0fcage_slots_used\x18\x04 \x01(\x05R\rcageSlotsUsed\"\xea\x02\n" +
	"\bHostInfo\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x120\n" +
	"\x04pool\x18\x02 \x01(\x0e2\x1c.agentcage.fleet.v1.HostPoolR\x04pool\x123\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1d.agentcage.fleet.v1.HostStateR\x05state\x12(\n" +
	"\x10cage_slots_total\x18\x04 \x01(\x05R\x0ecageSlotsTotal\x12&\n" +
	"\x0fcage_slots_used\x18\x05 \x01(\x05R\rcageSlotsUsed\x12\x1f\n" +
	"\vvcpus_total\x18\x06 \x01(\x05R\n" +
	"vcpusTotal\x12\x1d\n" +
	"\n" +
	"vcpus_used\x18\a \x01(\x05R\tvcpusUsed\x12&\n" +
	"\x0fmemory_mb_total\x18\b \x01(\x05R\rmemoryMbTotal\x12$\n" +
	"\x0ememory_mb_used\x18\t \x01(\x05R\fmemoryMbUsed\"\xa2\x01\n" +
	"\vFleetStatus\x12\x1f\n" +
	"\vtotal_hosts\x18\x01 \x01(\x05R\n" +
	"totalHosts\x124\n" +
	"\x05pools\x18\x02 \x03(\v2\x1e.agentcage.fleet.v1.PoolStatusR\x05pools\x12<\n" +
	"\x1acapacity_utilization_ratio\x18\x03 \x01(\x02R\x18capacityUtilizationRatio\"\x17\n" +
	"\x15GetFleetStatusRequest\"Q\n" +
	"\x16GetFleetStatusResponse\x127\n" +
	"\x06status\x18\x01 \x01(\v2\x1f.agentcage.fleet.v1.FleetStatusR\x06status\"Y\n" +
	"\x10DrainHostRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\x13\n" +
	"\x11DrainHostResponse\"Q\n" +
	"\x10ListHostsRequest\x12=\n" +
	"\vpool_filter\x18\x01 \x01(\x0e2\x1c.agentcage.fleet.v1.HostPoolR\n" +
	"poolFilter\"G\n" +
	"\x11ListHostsResponse\x122\n" +
	"\x05hosts\x18\x01 \x03(\v2\x1c.agentcage.fleet.v1.HostInfoR\x05hosts\"\x14\n" +
	"\x12GetCapacityRequest\"}\n" +
	"\x13GetCapacityResponse\x124\n" +
	"\x05pools\x18\x01 \x03(\v2\x1e.agentcage.fleet.v1.PoolStatusR\x05pools\x120\n" +
	"\x14available_cage_slots\x18\x02 \x01(\x05R\x12availableCageSlots*\x83\x01\n" +
	"\bHostPool\x12\x19\n" +
	"\x15HOST_POOL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10HOST_POOL_ACTIVE\x10\x01\x12\x12\n" +
	"\x0eHOST_POOL_WARM\x10\x02\x12\x1a\n" +
	"\x16HOST_POOL_PROVISIONING\x10\x03\x12\x16\n" +
	"\x12HOST_POOL_DRAINING\x10\x04*\xa0\x01\n" +
	"\tHostState\x12\x1a\n" +
	"\x16HOST_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17HOST_STATE_INITIALIZING\x10\x01\x12\x14\n" +
	"\x10HOST_STATE_READY\x10\x02\x12\x13\n" +
	"\x0fHOST_STATE_BUSY\x10\x03\x12\x17\n" +
	"\x13HOST_STATE_DRAINING\x10\x04\x12\x16\n" +
	"\x12HOST_STATE_OFFLINE\x10\x052\x8b\x03\n" +
	"\fFleetService\x12g\n" +
	"\x0eGetFleetStatus\x12).agentcage.fleet.v1.GetFleetStatusRequest\x1a*.agentcage.fleet.v1.GetFleetStatusResponse\x12X\n" +
	"\tListHosts\x12$.agentcage.fleet.v1.ListHostsRequest\x1a%.agentcage.fleet.v1.ListHostsResponse\x12X\n" +
	"\tDrainHost\x12$.agentcage.fleet.v1.DrainHostRequest\x1a%.agentcage.fleet.v1.DrainHostResponse\x12^\n" +
	"\vGetCapacity\x12&.agentcage.fleet.v1.GetCapacityRequest\x1a'.agentcage.fleet.v1.GetCapacityResponseB(Z&github.com/okedeji/agentcage/api/protob\x06proto3"

var (
	file_api_proto_fleet_proto_rawDescOnce sync.Once
	file_api_proto_fleet_proto_rawDescData []byte
)

func file_api_proto_fleet_proto_rawDescGZIP() []byte {
	file_api_proto_fleet_proto_rawDescOnce.Do(func() {
		file_api_proto_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_fleet_proto_rawDesc), len(file_api_proto_fleet_proto_rawDesc)))
	})
	return file_api_proto_fleet_proto_rawDescData
}

var file_api_proto_fleet_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_fleet_proto_goTypes = []any{
	(HostPool)(0),                  // 0: agentcage.fleet.v1.HostPool
	(HostState)(0),                 // 1: agentcage.fleet.v1.HostState
	(*PoolStatus)(nil),             // 2: agentcage.fleet.v1.PoolStatus
	(*HostInfo)(nil),               // 3: agentcage.fleet.v1.HostInfo
	(*FleetStatus)(nil),            // 4: agentcage.fleet.v1.FleetStatus
	(*GetFleetStatusRequest)(nil),  // 5: agentcage.fleet.v1.GetFleetStatusRequest
	(*GetFleetStatusResponse)(nil), // 6: agentcage.fleet.v1.GetFleetStatusResponse
	(*DrainHostRequest)(nil),       // 7: agentcage.fleet.v1.DrainHostRequest
	(*DrainHostResponse)(nil),      // 8: agentcage.fleet.v1.DrainHostResponse
	(*ListHostsRequest)(nil),       // 9: agentcage.fleet.v1.ListHostsRequest
	(*ListHostsResponse)(nil),      // 10: agentcage.fleet.v1.ListHostsResponse
	(*GetCapacityRequest)(nil),     // 11: agentcage.fleet.v1.GetCapacityRequest
	(*GetCapacityResponse)(nil),    // 12: agentcage.fleet.v1.GetCapacityResponse
}
var file_api_proto_fleet_proto_depIdxs = []int32{
	0,  // 0: agentcage.fleet.v1.PoolStatus.pool:type_name -> agentcage.fleet.v1.HostPool
	0,  // 1: agentcage.fleet.v1.HostInfo.pool:type_name -> agentcage.fleet.v1.HostPool
	1,  // 2: agentcage.fleet.v1.HostInfo.state:type_name -> agentcage.fleet.v1.HostState
	2,  // 3: agentcage.fleet.v1.FleetStatus.pools:type_name -> agentcage.fleet.v1.PoolStatus
	4,  // 4: agentcage.fleet.v1.GetFleetStatusResponse.status:type_name -> agentcage.fleet.v1.FleetStatus
	0,  // 5: agentcage.fleet.v1.ListHostsRequest.pool_filter:type_name -> agentcage.fleet.v1.HostPool
	3,  // 6: agentcage.fleet.v1.ListHostsResponse.hosts:type_name -> agentcage.fleet.v1.HostInfo
	2,  // 7: agentcage.fleet.v1.GetCapacityResponse.pools:type_name -> agentcage.fleet.v1.PoolStatus
	5,  // 8: agentcage.fleet.v1.FleetService.GetFleetStatus:input_type -> agentcage.fleet.v1.GetFleetStatusRequest
	9,  // 9: agentcage.fleet.v1.FleetService.ListHosts:input_type -> agentcage.fleet.v1.ListHostsRequest
	7,  // 10: agentcage.fleet.v1.FleetService.DrainHost:input_type -> agentcage.fleet.v1.DrainHostRequest
	11, // 11: agentcage.fleet.v1.FleetService.GetCapacity:input_type -> agentcage.fleet.v1.GetCapacityRequest
	6,  // 12: agentcage.fleet.v1.FleetService.GetFleetStatus:output_type -> agentcage.fleet.v1.GetFleetStatusResponse
	10, // 13: agentcage.fleet.v1.FleetService.ListHosts:output_type -> agentcage.fleet.v1.ListHostsResponse
	8,  // 14: agentcage.fleet.v1.FleetService.DrainHost:output_type -> agentcage.fleet.v1.DrainHostResponse
	12, // 15: agentcage.fleet.v1.FleetService.GetCapacity:output_type -> agentcage.fleet.v1.GetCapacityResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_proto_fleet_proto_init() }
func file_api_proto_fleet_proto_init() {
	if File_api_proto_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_fleet_proto_rawDesc), len(file_api_proto_fleet_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_fleet_proto_goTypes,
		DependencyIndexes: file_api_proto_fleet_proto_depIdxs,
		EnumInfos:         file_api_proto_fleet_proto_enumTypes,
		MessageInfos:      file_api_proto_fleet_proto_msgTypes,
	}.Build()
	File_api_proto_fleet_proto = out.File
	file_api_proto_fleet_proto_goTypes = nil
	file_api_proto_fleet_proto_depIdxs = nil
}
