// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/intervention.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterventionType int32

const (
	InterventionType_INTERVENTION_TYPE_UNSPECIFIED         InterventionType = 0
	InterventionType_INTERVENTION_TYPE_TRIPWIRE_ESCALATION InterventionType = 1
	InterventionType_INTERVENTION_TYPE_PAYLOAD_REVIEW      InterventionType = 2
	InterventionType_INTERVENTION_TYPE_REPORT_REVIEW       InterventionType = 3
	InterventionType_INTERVENTION_TYPE_PROOF_GAP           InterventionType = 4
)

// Enum value maps for InterventionType.
var (
	InterventionType_name = map[int32]string{
		0: "INTERVENTION_TYPE_UNSPECIFIED",
		1: "INTERVENTION_TYPE_TRIPWIRE_ESCALATION",
		2: "INTERVENTION_TYPE_PAYLOAD_REVIEW",
		3: "INTERVENTION_TYPE_REPORT_REVIEW",
		4: "INTERVENTION_TYPE_PROOF_GAP",
	}
	InterventionType_value = map[string]int32{
		"INTERVENTION_TYPE_UNSPECIFIED":         0,
		"INTERVENTION_TYPE_TRIPWIRE_ESCALATION": 1,
		"INTERVENTION_TYPE_PAYLOAD_REVIEW":      2,
		"INTERVENTION_TYPE_REPORT_REVIEW":       3,
		"INTERVENTION_TYPE_PROOF_GAP":           4,
	}
)

func (x InterventionType) Enum() *InterventionType {
	p := new(InterventionType)
	*p = x
	return p
}

func (x InterventionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterventionType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_intervention_proto_enumTypes[0].Descriptor()
}

func (InterventionType) Type() protoreflect.EnumType {
	return &file_api_proto_intervention_proto_enumTypes[0]
}

func (x InterventionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterventionType.Descriptor instead.
func (InterventionType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{0}
}

type ProofGapAction int32

const (
	ProofGapAction_PROOF_GAP_ACTION_UNSPECIFIED ProofGapAction = 0
	ProofGapAction_PROOF_GAP_ACTION_RETRY       ProofGapAction = 1
	ProofGapAction_PROOF_GAP_ACTION_SKIP        ProofGapAction = 2
)

// Enum value maps for ProofGapAction.
var (
	ProofGapAction_name = map[int32]string{
		0: "PROOF_GAP_ACTION_UNSPECIFIED",
		1: "PROOF_GAP_ACTION_RETRY",
		2: "PROOF_GAP_ACTION_SKIP",
	}
	ProofGapAction_value = map[string]int32{
		"PROOF_GAP_ACTION_UNSPECIFIED": 0,
		"PROOF_GAP_ACTION_RETRY":       1,
		"PROOF_GAP_ACTION_SKIP":        2,
	}
)

func (x ProofGapAction) Enum() *ProofGapAction {
	p := new(ProofGapAction)
	*p = x
	return p
}

func (x ProofGapAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProofGapAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_intervention_proto_enumTypes[1].Descriptor()
}

func (ProofGapAction) Type() protoreflect.EnumType {
	return &file_api_proto_intervention_proto_enumTypes[1]
}

func (x ProofGapAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProofGapAction.Descriptor instead.
func (ProofGapAction) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{1}
}

type InterventionAction int32

const (
	InterventionAction_INTERVENTION_ACTION_UNSPECIFIED       InterventionAction = 0
	InterventionAction_INTERVENTION_ACTION_RESUME            InterventionAction = 1
	InterventionAction_INTERVENTION_ACTION_ADJUST_AND_RESUME InterventionAction = 2
	InterventionAction_INTERVENTION_ACTION_KILL              InterventionAction = 3
	InterventionAction_INTERVENTION_ACTION_ALLOW             InterventionAction = 4
	InterventionAction_INTERVENTION_ACTION_BLOCK             InterventionAction = 5
)

// Enum value maps for InterventionAction.
var (
	InterventionAction_name = map[int32]string{
		0: "INTERVENTION_ACTION_UNSPECIFIED",
		1: "INTERVENTION_ACTION_RESUME",
		2: "INTERVENTION_ACTION_ADJUST_AND_RESUME",
		3: "INTERVENTION_ACTION_KILL",
		4: "INTERVENTION_ACTION_ALLOW",
		5: "INTERVENTION_ACTION_BLOCK",
	}
	InterventionAction_value = map[string]int32{
		"INTERVENTION_ACTION_UNSPECIFIED":       0,
		"INTERVENTION_ACTION_RESUME":            1,
		"INTERVENTION_ACTION_ADJUST_AND_RESUME": 2,
		"INTERVENTION_ACTION_KILL":              3,
		"INTERVENTION_ACTION_ALLOW":             4,
		"INTERVENTION_ACTION_BLOCK":             5,
	}
)

func (x InterventionAction) Enum() *InterventionAction {
	p := new(InterventionAction)
	*p = x
	return p
}

func (x InterventionAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterventionAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_intervention_proto_enumTypes[2].Descriptor()
}

func (InterventionAction) Type() protoreflect.EnumType {
	return &file_api_proto_intervention_proto_enumTypes[2]
}

func (x InterventionAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterventionAction.Descriptor instead.
func (InterventionAction) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{2}
}

type InterventionStatus int32

const (
	InterventionStatus_INTERVENTION_STATUS_UNSPECIFIED InterventionStatus = 0
	InterventionStatus_INTERVENTION_STATUS_PENDING     InterventionStatus = 1
	InterventionStatus_INTERVENTION_STATUS_RESOLVED    InterventionStatus = 2
	InterventionStatus_INTERVENTION_STATUS_TIMED_OUT   InterventionStatus = 3
)

// Enum value maps for InterventionStatus.
var (
	InterventionStatus_name = map[int32]string{
		0: "INTERVENTION_STATUS_UNSPECIFIED",
		1: "INTERVENTION_STATUS_PENDING",
		2: "INTERVENTION_STATUS_RESOLVED",
		3: "INTERVENTION_STATUS_TIMED_OUT",
	}
	InterventionStatus_value = map[string]int32{
		"INTERVENTION_STATUS_UNSPECIFIED": 0,
		"INTERVENTION_STATUS_PENDING":     1,
		"INTERVENTION_STATUS_RESOLVED":    2,
		"INTERVENTION_STATUS_TIMED_OUT":   3,
	}
)

func (x InterventionStatus) Enum() *InterventionStatus {
	p := new(InterventionStatus)
	*p = x
	return p
}

func (x InterventionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterventionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_intervention_proto_enumTypes[3].Descriptor()
}

func (InterventionStatus) Type() protoreflect.EnumType {
	return &file_api_proto_intervention_proto_enumTypes[3]
}

func (x InterventionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterventionStatus.Descriptor instead.
func (InterventionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{3}
}

type InterventionPriority int32

const (
	InterventionPriority_INTERVENTION_PRIORITY_UNSPECIFIED InterventionPriority = 0
	InterventionPriority_INTERVENTION_PRIORITY_LOW         InterventionPriority = 1
	InterventionPriority_INTERVENTION_PRIORITY_MEDIUM      InterventionPriority = 2
	InterventionPriority_INTERVENTION_PRIORITY_HIGH        InterventionPriority = 3
	InterventionPriority_INTERVENTION_PRIORITY_CRITICAL    InterventionPriority = 4
)

// Enum value maps for InterventionPriority.
var (
	InterventionPriority_name = map[int32]string{
		0: "INTERVENTION_PRIORITY_UNSPECIFIED",
		1: "INTERVENTION_PRIORITY_LOW",
		2: "INTERVENTION_PRIORITY_MEDIUM",
		3: "INTERVENTION_PRIORITY_HIGH",
		4: "INTERVENTION_PRIORITY_CRITICAL",
	}
	InterventionPriority_value = map[string]int32{
		"INTERVENTION_PRIORITY_UNSPECIFIED": 0,
		"INTERVENTION_PRIORITY_LOW":         1,
		"INTERVENTION_PRIORITY_MEDIUM":      2,
		"INTERVENTION_PRIORITY_HIGH":        3,
		"INTERVENTION_PRIORITY_CRITICAL":    4,
	}
)

func (x InterventionPriority) Enum() *InterventionPriority {
	p := new(InterventionPriority)
	*p = x
	return p
}

func (x InterventionPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterventionPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_intervention_proto_enumTypes[4].Descriptor()
}

func (InterventionPriority) Type() protoreflect.EnumType {
	return &file_api_proto_intervention_proto_enumTypes[4]
}

func (x InterventionPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterventionPriority.Descriptor instead.
func (InterventionPriority) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{4}
}

type ReviewDecision int32

const (
	ReviewDecision_REVIEW_DECISION_UNSPECIFIED    ReviewDecision = 0
	ReviewDecision_REVIEW_DECISION_APPROVE        ReviewDecision = 1
	ReviewDecision_REVIEW_DECISION_REQUEST_RETEST ReviewDecision = 2
	ReviewDecision_REVIEW_DECISION_REJECT         ReviewDecision = 3
)

// Enum value maps for ReviewDecision.
var (
	ReviewDecision_name = map[int32]string{
		0: "REVIEW_DECISION_UNSPECIFIED",
		1: "REVIEW_DECISION_APPROVE",
		2: "REVIEW_DECISION_REQUEST_RETEST",
		3: "REVIEW_DECISION_REJECT",
	}
	ReviewDecision_value = map[string]int32{
		"REVIEW_DECISION_UNSPECIFIED":    0,
		"REVIEW_DECISION_APPROVE":        1,
		"REVIEW_DECISION_REQUEST_RETEST": 2,
		"REVIEW_DECISION_REJECT":         3,
	}
)

func (x ReviewDecision) Enum() *ReviewDecision {
	p := new(ReviewDecision)
	*p = x
	return p
}

func (x ReviewDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_intervention_proto_enumTypes[5].Descriptor()
}

func (ReviewDecision) Type() protoreflect.EnumType {
	return &file_api_proto_intervention_proto_enumTypes[5]
}

func (x ReviewDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewDecision.Descriptor instead.
func (ReviewDecision) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{5}
}

type InterventionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InterventionId string                 `protobuf:"bytes,1,opt,name=intervention_id,json=interventionId,proto3" json:"intervention_id,omitempty"`
	Type           InterventionType       `protobuf:"varint,2,opt,name=type,proto3,enum=agentcage.intervention.v1.InterventionType" json:"type,omitempty"`
	Status         InterventionStatus     `protobuf:"varint,3,opt,name=status,proto3,enum=agentcage.intervention.v1.InterventionStatus" json:"status,omitempty"`
	Priority       InterventionPriority   `protobuf:"varint,4,opt,name=priority,proto3,enum=agentcage.intervention.v1.InterventionPriority" json:"priority,omitempty"`
	CageId         string                 `protobuf:"bytes,5,opt,name=cage_id,json=cageId,proto3" json:"cage_id,omitempty"`
	AssessmentId   string                 `protobuf:"bytes,6,opt,name=assessment_id,json=assessmentId,proto3" json:"assessment_id,omitempty"`
	Description    string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	ContextData    []byte                 `protobuf:"bytes,8,opt,name=context_data,json=contextData,proto3" json:"context_data,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ResolvedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	Timeout        *durationpb.Duration   `protobuf:"bytes,11,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InterventionInfo) Reset() {
	*x = InterventionInfo{}
	mi := &file_api_proto_intervention_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterventionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterventionInfo) ProtoMessage() {}

func (x *InterventionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intervention_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterventionInfo.ProtoReflect.Descriptor instead.
func (*InterventionInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{0}
}

func (x *InterventionInfo) GetInterventionId() string {
	if x != nil {
		return x.InterventionId
	}
	return ""
}

func (x *InterventionInfo) GetType() InterventionType {
	if x != nil {
		return x.Type
	}
	return InterventionType_INTERVENTION_TYPE_UNSPECIFIED
}

func (x *InterventionInfo) GetStatus() InterventionStatus {
	if x != nil {
		return x.Status
	}
	return InterventionStatus_INTERVENTION_STATUS_UNSPECIFIED
}

func (x *InterventionInfo) GetPriority() InterventionPriority {
	if x != nil {
		return x.Priority
	}
	return InterventionPriority_INTERVENTION_PRIORITY_UNSPECIFIED
}

func (x *InterventionInfo) GetCageId() string {
	if x != nil {
		return x.CageId
	}
	return ""
}

func (x *InterventionInfo) GetAssessmentId() string {
	if x != nil {
		return x.AssessmentId
	}
	return ""
}

func (x *InterventionInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InterventionInfo) GetContextData() []byte {
	if x != nil {
		return x.ContextData
	}
	return nil
}

func (x *InterventionInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InterventionInfo) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

func (x *InterventionInfo) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type FindingAdjustment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FindingId        string                 `protobuf:"bytes,1,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"`
	SeverityOverride string                 `protobuf:"bytes,2,opt,name=severity_override,json=severityOverride,proto3" json:"severity_override,omitempty"`
	Rationale        string                 `protobuf:"bytes,3,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindingAdjustment) Reset() {
	*x = FindingAdjustment{}
	mi := &file_api_proto_intervention_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingAdjustment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingAdjustment) ProtoMessage() {}

func (x *FindingAdjustment) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intervention_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingAdjustment.ProtoReflect.Descriptor instead.
func (*FindingAdjustment) Descriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{1}
}

func (x *FindingAdjustment) GetFindingId() string {
	if x != nil {
		return x.FindingId
	}
	return ""
}

func (x *FindingAdjustment) GetSeverityOverride() string {
	if x != nil {
		return x.SeverityOverride
	}
	return ""
}

func (x *FindingAdjustment) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type ResolveCageInterventionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InterventionId string                 `protobuf:"bytes,1,opt,name=intervention_id,json=interventionId,proto3" json:"intervention_id,omitempty"`
	Action         InterventionAction     `protobuf:"varint,2,opt,name=action,proto3,enum=agentcage.intervention.v1.InterventionAction" json:"action,omitempty"`
	Rationale      string                 `protobuf:"bytes,3,opt,name=rationale,proto3" json:"rationale,omitempty"`
	Adjustments    map[string]string      `protobuf:"bytes,4,rep,name=adjustments,proto3" json:"adjustments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveCageInterventionRequest) Reset() {
	*x = ResolveCageInterventionRequest{}
	mi := &file_api_proto_intervention_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCageInterventionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCageInterventionRequest) ProtoMessage() {}

func (x *ResolveCageInterventionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intervention_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCageInterventionRequest.ProtoReflect.Descriptor instead.
func (*ResolveCageInterventionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveCageInterventionRequest) GetInterventionId() string {
	if x != nil {
		return x.InterventionId
	}
	return ""
}

func (x *ResolveCageInterventionRequest) GetAction() InterventionAction {
	if x != nil {
		return x.Action
	}
	return InterventionAction_INTERVENTION_ACTION_UNSPECIFIED
}

func (x *ResolveCageInterventionRequest) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *ResolveCageInterventionRequest) GetAdjustments() map[string]string {
	if x != nil {
		return x.Adjustments
	}
	return nil
}

type ResolveCageInterventionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCageInterventionResponse) Reset() {
	*x = ResolveCageInterventionResponse{}
	mi := &file_api_proto_intervention_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCageInterventionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCageInterventionResponse) ProtoMessage() {}

func (x *ResolveCageInterventionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intervention_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCageInterventionResponse.ProtoReflect.Descriptor instead.
func (*ResolveCageInterventionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{3}
}

type ResolveAssessmentReviewRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InterventionId string                 `protobuf:"bytes,1,opt,name=intervention_id,json=interventionId,proto3" json:"intervention_id,omitempty"`
	Decision       ReviewDecision         `protobuf:"varint,2,opt,name=decision,proto3,enum=agentcage.intervention.v1.ReviewDecision" json:"decision,omitempty"`
	Rationale      string                 `protobuf:"bytes,3,opt,name=rationale,proto3" json:"rationale,omitempty"`
	Adjustments    []*FindingAdjustment   `protobuf:"bytes,4,rep,name=adjustments,proto3" json:"adjustments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveAssessmentReviewRequest) Reset() {
	*x = ResolveAssessmentReviewRequest{}
	mi := &file_api_proto_intervention_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAssessmentReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAssessmentReviewRequest) ProtoMessage() {}

func (x *ResolveAssessmentReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intervention_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAssessmentReviewRequest.ProtoReflect.Descriptor instead.
func (*ResolveAssessmentReviewRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveAssessmentReviewRequest) GetInterventionId() string {
	if x != nil {
		return x.InterventionId
	}
	return ""
}

func (x *ResolveAssessmentReviewRequest) GetDecision() ReviewDecision {
	if x != nil {
		return x.Decision
	}
	return ReviewDecision_REVIEW_DECISION_UNSPECIFIED
}

func (x *ResolveAssessmentReviewRequest) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *ResolveAssessmentReviewRequest) GetAdjustments() []*FindingAdjustment {
	if x != nil {
		return x.Adjustments
	}
	return nil
}

type ResolveAssessmentReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAssessmentReviewResponse) Reset() {
	*x = ResolveAssessmentReviewResponse{}
	mi := &file_api_proto_intervention_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAssessmentReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAssessmentReviewResponse) ProtoMessage() {}

func (x *ResolveAssessmentReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intervention_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAssessmentReviewResponse.ProtoReflect.Descriptor instead.
func (*ResolveAssessmentReviewResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{5}
}

type ResolveProofGapRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InterventionId string                 `protobuf:"bytes,1,opt,name=intervention_id,json=interventionId,proto3" json:"intervention_id,omitempty"`
	Action         ProofGapAction         `protobuf:"varint,2,opt,name=action,proto3,enum=agentcage.intervention.v1.ProofGapAction" json:"action,omitempty"`
	Rationale      string                 `protobuf:"bytes,3,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveProofGapRequest) Reset() {
	*x = ResolveProofGapRequest{}
	mi := &file_api_proto_intervention_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProofGapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProofGapRequest) ProtoMessage() {}

func (x *ResolveProofGapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intervention_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProofGapRequest.ProtoReflect.Descriptor instead.
func (*ResolveProofGapRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveProofGapRequest) GetInterventionId() string {
	if x != nil {
		return x.InterventionId
	}
	return ""
}

func (x *ResolveProofGapRequest) GetAction() ProofGapAction {
	if x != nil {
		return x.Action
	}
	return ProofGapAction_PROOF_GAP_ACTION_UNSPECIFIED
}

func (x *ResolveProofGapRequest) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type ResolveProofGapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveProofGapResponse) Reset() {
	*x = ResolveProofGapResponse{}
	mi := &file_api_proto_intervention_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProofGapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProofGapResponse) ProtoMessage() {}

func (x *ResolveProofGapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intervention_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProofGapResponse.ProtoReflect.Descriptor instead.
func (*ResolveProofGapResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{7}
}

type ListInterventionsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter       InterventionStatus     `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=agentcage.intervention.v1.InterventionStatus" json:"status_filter,omitempty"`
	TypeFilter         InterventionType       `protobuf:"varint,2,opt,name=type_filter,json=typeFilter,proto3,enum=agentcage.intervention.v1.InterventionType" json:"type_filter,omitempty"`
	AssessmentIdFilter string                 `protobuf:"bytes,3,opt,name=assessment_id_filter,json=assessmentIdFilter,proto3" json:"assessment_id_filter,omitempty"`
	PageSize           int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken          string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListInterventionsRequest) Reset() {
	*x = ListInterventionsRequest{}
	mi := &file_api_proto_intervention_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterventionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterventionsRequest) ProtoMessage() {}

func (x *ListInterventionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intervention_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterventionsRequest.ProtoReflect.Descriptor instead.
func (*ListInterventionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{8}
}

func (x *ListInterventionsRequest) GetStatusFilter() InterventionStatus {
	if x != nil {
		return x.StatusFilter
	}
	return InterventionStatus_INTERVENTION_STATUS_UNSPECIFIED
}

func (x *ListInterventionsRequest) GetTypeFilter() InterventionType {
	if x != nil {
		return x.TypeFilter
	}
	return InterventionType_INTERVENTION_TYPE_UNSPECIFIED
}

func (x *ListInterventionsRequest) GetAssessmentIdFilter() string {
	if x != nil {
		return x.AssessmentIdFilter
	}
	return ""
}

func (x *ListInterventionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInterventionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListInterventionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interventions []*InterventionInfo    `protobuf:"bytes,1,rep,name=interventions,proto3" json:"interventions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterventionsResponse) Reset() {
	*x = ListInterventionsResponse{}
	mi := &file_api_proto_intervention_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterventionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterventionsResponse) ProtoMessage() {}

func (x *ListInterventionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_intervention_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterventionsResponse.ProtoReflect.Descriptor instead.
func (*ListInterventionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_intervention_proto_rawDescGZIP(), []int{9}
}

func (x *ListInterventionsResponse) GetInterventions() []*InterventionInfo {
	if x != nil {
		return x.Interventions
	}
	return nil
}

func (x *ListInterventionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_api_proto_intervention_proto protoreflect.FileDescriptor

const file_api_proto_intervention_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/intervention.proto\x12\x19agentcage.intervention.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x04\n" +
	"\x10InterventionInfo\x12'\n" +
	"\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\x12?\n" +
	"\x04type\x18\x02 \x01(\x0e2+.agentcage.intervention.v1.InterventionTypeR\x04type\x12E\n" +
	"\x06status\x18\x03 \x01(\x0e2-.agentcage.intervention.v1.InterventionStatusR\x06status\x12K\n" +
	"\bpriority\x18\x04 \x01(\x0e2/.agentcage.intervention.v1.InterventionPriorityR\bpriority\x12\x17\n" +
	"\acage_id\x18\x05 \x01(\tR\x06cageId\x12#\n" +
	"\rassessment_id\x18\x06 \x01(\tR\fassessmentId\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12!\n" +
	"\fcontext_data\x18\b \x01(\fR\vcontextData\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vresolved_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\x123\n" +
	"\atimeout\x18\v \x01(\v2\x19.google.protobuf.DurationR\atimeout\"}\n" +
	"\x11FindingAdjustment\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x01 \x01(\tR\tfindingId\x12+\n" +
	"\x11severity_override\x18\x02 \x01(\tR\x10severityOverride\x12\x1c\n" +
	"\trationale\x18\x03 \x01(\tR\trationale\"\xdc\x02\n" +
	"\x1eResolveCageInterventionRequest\x12'\n" +
	"\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\x12E\n" +
	"\x06action\x18\x02 \x01(\x0e2-.agentcage.intervention.v1.InterventionActionR\x06action\x12\x1c\n" +
	"\trationale\x18\x03 \x01(\tR\trationale\x12l\n" +
	"\vadjustments\x18\x04 \x03(\v2J.agentcage.intervention.v1.ResolveCageInterventionRequest.AdjustmentsEntryR\vadjustments\x1a>\n" +
	"\x10AdjustmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\x1fResolveCageInterventionResponse\"\xfe\x01\n" +
	"\x1eResolveAssessmentReviewRequest\x12'\n" +
	"\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\x12E\n" +
	"\bdecision\x18\x02 \x01(\x0e2).agentcage.intervention.v1.ReviewDecisionR\bdecision\x12\x1c\n" +
	"\trationale\x18\x03 \x01(\tR\trationale\x12N\n" +
	"\vadjustments\x18\x04 \x03(\v2,.agentcage.intervention.v1.FindingAdjustmentR\vadjustments\"!\n" +
	"\x1fResolveAssessmentReviewResponse\"\xa2\x01\n" +
	"\x16ResolveProofGapRequest\x12'\n" +
	"\x0fintervention_id\x18\x01 \x01(\tR\x0einterventionId\x12A\n" +
	"\x06action\x18\x02 \x01(\x0e2).agentcage.intervention.v1.ProofGapActionR\x06action\x12\x1c\n" +
	"\trationale\x18\x03 \x01(\tR\trationale\"\x19\n" +
	"\x17ResolveProofGapResponse\"\xaa\x02\n" +
	"\x18ListInterventionsRequest\x12R\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2-.agentcage.intervention.v1.InterventionStatusR\fstatusFilter\x12L\n" +
	"\vtype_filter\x18\x02 \x01(\x0e2+.agentcage.intervention.v1.InterventionTypeR\n" +
	"typeFilter\x120\n" +
	"\x14assessment_id_filter\x18\x03 \x01(\tR\x12assessmentIdFilter\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x96\x01\n" +
	"\x19ListInterventionsResponse\x12Q\n" +
	"\rinterventions\x18\x01 \x03(\v2+.agentcage.intervention.v1.InterventionInfoR\rinterventions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*\xcc\x01\n" +
	"\x10InterventionType\x12!\n" +
	"\x1dINTERVENTION_TYPE_UNSPECIFIED\x10\x00\x12)\n" +
	"%INTERVENTION_TYPE_TRIPWIRE_ESCALATION\x10\x01\x12$\n" +
	" INTERVENTION_TYPE_PAYLOAD_REVIEW\x10\x02\x12#\n" +
	"\x1fINTERVENTION_TYPE_REPORT_REVIEW\x10\x03\x12\x1f\n" +
	"\x1bINTERVENTION_TYPE_PROOF_GAP\x10\x04*i\n" +
	"\x0eProofGapAction\x12 \n" +
	"\x1cPROOF_GAP_ACTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PROOF_GAP_ACTION_RETRY\x10\x01\x12\x19\n" +
	"\x15PROOF_GAP_ACTION_SKIP\x10\x02*\xe0\x01\n" +
	"\x12InterventionAction\x12#\n" +
	"\x1fINTERVENTION_ACTION_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aINTERVENTION_ACTION_RESUME\x10\x01\x12)\n" +
	"%INTERVENTION_ACTION_ADJUST_AND_RESUME\x10\x02\x12\x1c\n" +
	"\x18INTERVENTION_ACTION_KILL\x10\x03\x12\x1d\n" +
	"\x19INTERVENTION_ACTION_ALLOW\x10\x04\x12\x1d\n" +
	"\x19INTERVENTION_ACTION_BLOCK\x10\x05*\x9f\x01\n" +
	"\x12InterventionStatus\x12#\n" +
	"\x1fINTERVENTION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bINTERVENTION_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cINTERVENTION_STATUS_RESOLVED\x10\x02\x12!\n" +
	"\x1dINTERVENTION_STATUS_TIMED_OUT\x10\x03*\xc2\x01\n" +
	"\x14InterventionPriority\x12%\n" +
	"!INTERVENTION_PRIORITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INTERVENTION_PRIORITY_LOW\x10\x01\x12 \n" +
	"\x1cINTERVENTION_PRIORITY_MEDIUM\x10\x02\x12\x1e\n" +
	"\x1aINTERVENTION_PRIORITY_HIGH\x10\x03\x12\"\n" +
	"\x1eINTERVENTION_PRIORITY_CRITICAL\x10\x04*\x8e\x01\n" +
	"\x0eReviewDecision\x12\x1f\n" +
	"\x1bREVIEW_DECISION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17REVIEW_DECISION_APPROVE\x10\x01\x12\"\n" +
	"\x1eREVIEW_DECISION_REQUEST_RETEST\x10\x02\x12\x1a\n" +
	"\x16REVIEW_DECISION_REJECT\x10\x032\xb5\x04\n" +
	"\x13InterventionService\x12~\n" +
	"\x11ListInterventions\x123.agentcage.intervention.v1.ListInterventionsRequest\x1a4.agentcage.intervention.v1.ListInterventionsResponse\x12\x90\x01\n" +
	"\x17ResolveCageIntervention\x129.agentcage.intervention.v1.ResolveCageInterventionRequest\x1a:.agentcage.intervention.v1.ResolveCageInterventionResponse\x12\x90\x01\n" +
	"\x17ResolveAssessmentReview\x129.agentcage.intervention.v1.ResolveAssessmentReviewRequest\x1a:.agentcage.intervention.v1.ResolveAssessmentReviewResponse\x12x\n" +
	"\x0fResolveProofGap\x121.agentcage.intervention.v1.ResolveProofGapRequest\x1a2.agentcage.intervention.v1.ResolveProofGapResponseB(Z&github.com/okedeji/agentcage/api/protob\x06proto3"

var (
	file_api_proto_intervention_proto_rawDescOnce sync.Once
	file_api_proto_intervention_proto_rawDescData []byte
)

func file_api_proto_intervention_proto_rawDescGZIP() []byte {
	file_api_proto_intervention_proto_rawDescOnce.Do(func() {
		file_api_proto_intervention_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_intervention_proto_rawDesc), len(file_api_proto_intervention_proto_rawDesc)))
	})
	return file_api_proto_intervention_proto_rawDescData
}

var file_api_proto_intervention_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_api_proto_intervention_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_intervention_proto_goTypes = []any{
	(InterventionType)(0),                   // 0: agentcage.intervention.v1.InterventionType
	(ProofGapAction)(0),                     // 1: agentcage.intervention.v1.ProofGapAction
	(InterventionAction)(0),                 // 2: agentcage.intervention.v1.InterventionAction
	(InterventionStatus)(0),                 // 3: agentcage.intervention.v1.InterventionStatus
	(InterventionPriority)(0),               // 4: agentcage.intervention.v1.InterventionPriority
	(ReviewDecision)(0),                     // 5: agentcage.intervention.v1.ReviewDecision
	(*InterventionInfo)(nil),                // 6: agentcage.intervention.v1.InterventionInfo
	(*FindingAdjustment)(nil),               // 7: agentcage.intervention.v1.FindingAdjustment
	(*ResolveCageInterventionRequest)(nil),  // 8: agentcage.intervention.v1.ResolveCageInterventionRequest
	(*ResolveCageInterventionResponse)(nil), // 9: agentcage.intervention.v1.ResolveCageInterventionResponse
	(*ResolveAssessmentReviewRequest)(nil),  // 10: agentcage.intervention.v1.ResolveAssessmentReviewRequest
	(*ResolveAssessmentReviewResponse)(nil), // 11: agentcage.intervention.v1.ResolveAssessmentReviewResponse
	(*ResolveProofGapRequest)(nil),          // 12: agentcage.intervention.v1.ResolveProofGapRequest
	(*ResolveProofGapResponse)(nil),         // 13: agentcage.intervention.v1.ResolveProofGapResponse
	(*ListInterventionsRequest)(nil),        // 14: agentcage.intervention.v1.ListInterventionsRequest
	(*ListInterventionsResponse)(nil),       // 15: agentcage.intervention.v1.ListInterventionsResponse
	nil,                                     // 16: agentcage.intervention.v1.ResolveCageInterventionRequest.AdjustmentsEntry
	(*timestamppb.Timestamp)(nil),           // 17: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),             // 18: google.protobuf.Duration
}
var file_api_proto_intervention_proto_depIdxs = []int32{
	0,  // 0: agentcage.intervention.v1.InterventionInfo.type:type_name -> agentcage.intervention.v1.InterventionType
	3,  // 1: agentcage.intervention.v1.InterventionInfo.status:type_name -> agentcage.intervention.v1.InterventionStatus
	4,  // 2: agentcage.intervention.v1.InterventionInfo.priority:type_name -> agentcage.intervention.v1.InterventionPriority
	17, // 3: agentcage.intervention.v1.InterventionInfo.created_at:type_name -> google.protobuf.Timestamp
	17, // 4: agentcage.intervention.v1.InterventionInfo.resolved_at:type_name -> google.protobuf.Timestamp
	18, // 5: agentcage.intervention.v1.InterventionInfo.timeout:type_name -> google.protobuf.Duration
	2,  // 6: agentcage.intervention.v1.ResolveCageInterventionRequest.action:type_name -> agentcage.intervention.v1.InterventionAction
	16, // 7: agentcage.intervention.v1.ResolveCageInterventionRequest.adjustments:type_name -> agentcage.intervention.v1.ResolveCageInterventionRequest.AdjustmentsEntry
	5,  // 8: agentcage.intervention.v1.ResolveAssessmentReviewRequest.decision:type_name -> agentcage.intervention.v1.ReviewDecision
	7,  // 9: agentcage.intervention.v1.ResolveAssessmentReviewRequest.adjustments:type_name -> agentcage.intervention.v1.FindingAdjustment
	1,  // 10: agentcage.intervention.v1.ResolveProofGapRequest.action:type_name -> agentcage.intervention.v1.ProofGapAction
	3,  // 11: agentcage.intervention.v1.ListInterventionsRequest.status_filter:type_name -> agentcage.intervention.v1.InterventionStatus
	0,  // 12: agentcage.intervention.v1.ListInterventionsRequest.type_filter:type_name -> agentcage.intervention.v1.InterventionType
	6,  // 13: agentcage.intervention.v1.ListInterventionsResponse.interventions:type_name -> agentcage.intervention.v1.InterventionInfo
	14, // 14: agentcage.intervention.v1.InterventionService.ListInterventions:input_type -> agentcage.intervention.v1.ListInterventionsRequest
	8,  // 15: agentcage.intervention.v1.InterventionService.ResolveCageIntervention:input_type -> agentcage.intervention.v1.ResolveCageInterventionRequest
	10, // 16: agentcage.intervention.v1.InterventionService.ResolveAssessmentReview:input_type -> agentcage.intervention.v1.ResolveAssessmentReviewRequest
	12, // 17: agentcage.intervention.v1.InterventionService.ResolveProofGap:input_type -> agentcage.intervention.v1.ResolveProofGapRequest
	15, // 18: agentcage.intervention.v1.InterventionService.ListInterventions:output_type -> agentcage.intervention.v1.ListInterventionsResponse
	9,  // 19: agentcage.intervention.v1.InterventionService.ResolveCageIntervention:output_type -> agentcage.intervention.v1.ResolveCageInterventionResponse
	11, // 20: agentcage.intervention.v1.InterventionService.ResolveAssessmentReview:output_type -> agentcage.intervention.v1.ResolveAssessmentReviewResponse
	13, // 21: agentcage.intervention.v1.InterventionService.ResolveProofGap:output_type -> agentcage.intervention.v1.ResolveProofGapResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_intervention_proto_init() }
func file_api_proto_intervention_proto_init() {
	if File_api_proto_intervention_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_intervention_proto_rawDesc), len(file_api_proto_intervention_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_intervention_proto_goTypes,
		DependencyIndexes: file_api_proto_intervention_proto_depIdxs,
		EnumInfos:         file_api_proto_intervention_proto_enumTypes,
		MessageInfos:      file_api_proto_intervention_proto_msgTypes,
	}.Build()
	File_api_proto_intervention_proto = out.File
	file_api_proto_intervention_proto_goTypes = nil
	file_api_proto_intervention_proto_depIdxs = nil
}
