// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/pack.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PackRequest_Metadata
	//	*PackRequest_Chunk
	Payload       isPackRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackRequest) Reset() {
	*x = PackRequest{}
	mi := &file_api_proto_pack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackRequest) ProtoMessage() {}

func (x *PackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackRequest.ProtoReflect.Descriptor instead.
func (*PackRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pack_proto_rawDescGZIP(), []int{0}
}

func (x *PackRequest) GetPayload() isPackRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PackRequest) GetMetadata() *PackMetadata {
	if x != nil {
		if x, ok := x.Payload.(*PackRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *PackRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*PackRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isPackRequest_Payload interface {
	isPackRequest_Payload()
}

type PackRequest_Metadata struct {
	Metadata *PackMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type PackRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*PackRequest_Metadata) isPackRequest_Payload() {}

func (*PackRequest_Chunk) isPackRequest_Payload() {}

// PackMetadata is sent as the first message in the stream.
type PackMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CagefileContent string                 `protobuf:"bytes,1,opt,name=cagefile_content,json=cagefileContent,proto3" json:"cagefile_content,omitempty"`
	DirectoryName   string                 `protobuf:"bytes,2,opt,name=directory_name,json=directoryName,proto3" json:"directory_name,omitempty"`
	Tag             string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PackMetadata) Reset() {
	*x = PackMetadata{}
	mi := &file_api_proto_pack_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackMetadata) ProtoMessage() {}

func (x *PackMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pack_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackMetadata.ProtoReflect.Descriptor instead.
func (*PackMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_pack_proto_rawDescGZIP(), []int{1}
}

func (x *PackMetadata) GetCagefileContent() string {
	if x != nil {
		return x.CagefileContent
	}
	return ""
}

func (x *PackMetadata) GetDirectoryName() string {
	if x != nil {
		return x.DirectoryName
	}
	return ""
}

func (x *PackMetadata) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type PackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PackResponse_Progress
	//	*PackResponse_Result
	Payload       isPackResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackResponse) Reset() {
	*x = PackResponse{}
	mi := &file_api_proto_pack_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackResponse) ProtoMessage() {}

func (x *PackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pack_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackResponse.ProtoReflect.Descriptor instead.
func (*PackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pack_proto_rawDescGZIP(), []int{2}
}

func (x *PackResponse) GetPayload() isPackResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PackResponse) GetProgress() *PackProgress {
	if x != nil {
		if x, ok := x.Payload.(*PackResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *PackResponse) GetResult() *PackResult {
	if x != nil {
		if x, ok := x.Payload.(*PackResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isPackResponse_Payload interface {
	isPackResponse_Payload()
}

type PackResponse_Progress struct {
	Progress *PackProgress `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type PackResponse_Result struct {
	Result *PackResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*PackResponse_Progress) isPackResponse_Payload() {}

func (*PackResponse_Result) isPackResponse_Payload() {}

type PackProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Percent       int32                  `protobuf:"varint,3,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackProgress) Reset() {
	*x = PackProgress{}
	mi := &file_api_proto_pack_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackProgress) ProtoMessage() {}

func (x *PackProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pack_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackProgress.ProtoReflect.Descriptor instead.
func (*PackProgress) Descriptor() ([]byte, []int) {
	return file_api_proto_pack_proto_rawDescGZIP(), []int{3}
}

func (x *PackProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *PackProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PackProgress) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type PackResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleRef     string                 `protobuf:"bytes,1,opt,name=bundle_ref,json=bundleRef,proto3" json:"bundle_ref,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Runtime       string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Entrypoint    string                 `protobuf:"bytes,5,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackResult) Reset() {
	*x = PackResult{}
	mi := &file_api_proto_pack_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackResult) ProtoMessage() {}

func (x *PackResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pack_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackResult.ProtoReflect.Descriptor instead.
func (*PackResult) Descriptor() ([]byte, []int) {
	return file_api_proto_pack_proto_rawDescGZIP(), []int{4}
}

func (x *PackResult) GetBundleRef() string {
	if x != nil {
		return x.BundleRef
	}
	return ""
}

func (x *PackResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PackResult) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *PackResult) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *PackResult) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *PackResult) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

var File_api_proto_pack_proto protoreflect.FileDescriptor

const file_api_proto_pack_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/pack.proto\x12\x11agentcage.pack.v1\"o\n" +
	"\vPackRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.agentcage.pack.v1.PackMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"r\n" +
	"\fPackMetadata\x12)\n" +
	"\x10cagefile_content\x18\x01 \x01(\tR\x0fcagefileContent\x12%\n" +
	"\x0edirectory_name\x18\x02 \x01(\tR\rdirectoryName\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\"\x91\x01\n" +
	"\fPackResponse\x12=\n" +
	"\bprogress\x18\x01 \x01(\v2\x1f.agentcage.pack.v1.PackProgressH\x00R\bprogress\x127\n" +
	"\x06result\x18\x02 \x01(\v2\x1d.agentcage.pack.v1.PackResultH\x00R\x06resultB\t\n" +
	"\apayload\"X\n" +
	"\fPackProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x05R\apercent\"\xaa\x01\n" +
	"\n" +
	"PackResult\x12\x1d\n" +
	"\n" +
	"bundle_ref\x18\x01 \x01(\tR\tbundleRef\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x05 \x01(\tR\n" +
	"entrypoint\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes2Z\n" +
	"\vPackService\x12K\n" +
	"\x04Pack\x12\x1e.agentcage.pack.v1.PackRequest\x1a\x1f.agentcage.pack.v1.PackResponse(\x010\x01B(Z&github.com/okedeji/agentcage/api/protob\x06proto3"

var (
	file_api_proto_pack_proto_rawDescOnce sync.Once
	file_api_proto_pack_proto_rawDescData []byte
)

func file_api_proto_pack_proto_rawDescGZIP() []byte {
	file_api_proto_pack_proto_rawDescOnce.Do(func() {
		file_api_proto_pack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_pack_proto_rawDesc), len(file_api_proto_pack_proto_rawDesc)))
	})
	return file_api_proto_pack_proto_rawDescData
}

var file_api_proto_pack_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_pack_proto_goTypes = []any{
	(*PackRequest)(nil),  // 0: agentcage.pack.v1.PackRequest
	(*PackMetadata)(nil), // 1: agentcage.pack.v1.PackMetadata
	(*PackResponse)(nil), // 2: agentcage.pack.v1.PackResponse
	(*PackProgress)(nil), // 3: agentcage.pack.v1.PackProgress
	(*PackResult)(nil),   // 4: agentcage.pack.v1.PackResult
}
var file_api_proto_pack_proto_depIdxs = []int32{
	1, // 0: agentcage.pack.v1.PackRequest.metadata:type_name -> agentcage.pack.v1.PackMetadata
	3, // 1: agentcage.pack.v1.PackResponse.progress:type_name -> agentcage.pack.v1.PackProgress
	4, // 2: agentcage.pack.v1.PackResponse.result:type_name -> agentcage.pack.v1.PackResult
	0, // 3: agentcage.pack.v1.PackService.Pack:input_type -> agentcage.pack.v1.PackRequest
	2, // 4: agentcage.pack.v1.PackService.Pack:output_type -> agentcage.pack.v1.PackResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_pack_proto_init() }
func file_api_proto_pack_proto_init() {
	if File_api_proto_pack_proto != nil {
		return
	}
	file_api_proto_pack_proto_msgTypes[0].OneofWrappers = []any{
		(*PackRequest_Metadata)(nil),
		(*PackRequest_Chunk)(nil),
	}
	file_api_proto_pack_proto_msgTypes[2].OneofWrappers = []any{
		(*PackResponse_Progress)(nil),
		(*PackResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_pack_proto_rawDesc), len(file_api_proto_pack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_pack_proto_goTypes,
		DependencyIndexes: file_api_proto_pack_proto_depIdxs,
		MessageInfos:      file_api_proto_pack_proto_msgTypes,
	}.Build()
	File_api_proto_pack_proto = out.File
	file_api_proto_pack_proto_goTypes = nil
	file_api_proto_pack_proto_depIdxs = nil
}
