// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/vault.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutSecretRequest) Reset() {
	*x = PutSecretRequest{}
	mi := &file_api_proto_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSecretRequest) ProtoMessage() {}

func (x *PutSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSecretRequest.ProtoReflect.Descriptor instead.
func (*PutSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_vault_proto_rawDescGZIP(), []int{0}
}

func (x *PutSecretRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PutSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutSecretRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutSecretResponse) Reset() {
	*x = PutSecretResponse{}
	mi := &file_api_proto_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSecretResponse) ProtoMessage() {}

func (x *PutSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSecretResponse.ProtoReflect.Descriptor instead.
func (*PutSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_vault_proto_rawDescGZIP(), []int{1}
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_api_proto_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_vault_proto_rawDescGZIP(), []int{2}
}

func (x *GetSecretRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *GetSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Redacted      bool                   `protobuf:"varint,2,opt,name=redacted,proto3" json:"redacted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_api_proto_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_vault_proto_rawDescGZIP(), []int{3}
}

func (x *GetSecretResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetSecretResponse) GetRedacted() bool {
	if x != nil {
		return x.Redacted
	}
	return false
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_api_proto_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_vault_proto_rawDescGZIP(), []int{4}
}

func (x *ListSecretsRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_api_proto_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_vault_proto_rawDescGZIP(), []int{5}
}

func (x *ListSecretsResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_api_proto_vault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_vault_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSecretRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *DeleteSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_api_proto_vault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_vault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_vault_proto_rawDescGZIP(), []int{7}
}

var File_api_proto_vault_proto protoreflect.FileDescriptor

const file_api_proto_vault_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/vault.proto\x12\x12agentcage.vault.v1\"P\n" +
	"\x10PutSecretRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\x13\n" +
	"\x11PutSecretResponse\":\n" +
	"\x10GetSecretRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"E\n" +
	"\x11GetSecretResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x1a\n" +
	"\bredacted\x18\x02 \x01(\bR\bredacted\"*\n" +
	"\x12ListSecretsRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\")\n" +
	"\x13ListSecretsResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"=\n" +
	"\x13DeleteSecretRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x16\n" +
	"\x14DeleteSecretResponse2\x85\x03\n" +
	"\fVaultService\x12X\n" +
	"\tPutSecret\x12$.agentcage.vault.v1.PutSecretRequest\x1a%.agentcage.vault.v1.PutSecretResponse\x12X\n" +
	"\tGetSecret\x12$.agentcage.vault.v1.GetSecretRequest\x1a%.agentcage.vault.v1.GetSecretResponse\x12^\n" +
	"\vListSecrets\x12&.agentcage.vault.v1.ListSecretsRequest\x1a'.agentcage.vault.v1.ListSecretsResponse\x12a\n" +
	"\fDeleteSecret\x12'.agentcage.vault.v1.DeleteSecretRequest\x1a(.agentcage.vault.v1.DeleteSecretResponseB(Z&github.com/okedeji/agentcage/api/protob\x06proto3"

var (
	file_api_proto_vault_proto_rawDescOnce sync.Once
	file_api_proto_vault_proto_rawDescData []byte
)

func file_api_proto_vault_proto_rawDescGZIP() []byte {
	file_api_proto_vault_proto_rawDescOnce.Do(func() {
		file_api_proto_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_vault_proto_rawDesc), len(file_api_proto_vault_proto_rawDesc)))
	})
	return file_api_proto_vault_proto_rawDescData
}

var file_api_proto_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_vault_proto_goTypes = []any{
	(*PutSecretRequest)(nil),     // 0: agentcage.vault.v1.PutSecretRequest
	(*PutSecretResponse)(nil),    // 1: agentcage.vault.v1.PutSecretResponse
	(*GetSecretRequest)(nil),     // 2: agentcage.vault.v1.GetSecretRequest
	(*GetSecretResponse)(nil),    // 3: agentcage.vault.v1.GetSecretResponse
	(*ListSecretsRequest)(nil),   // 4: agentcage.vault.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),  // 5: agentcage.vault.v1.ListSecretsResponse
	(*DeleteSecretRequest)(nil),  // 6: agentcage.vault.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil), // 7: agentcage.vault.v1.DeleteSecretResponse
}
var file_api_proto_vault_proto_depIdxs = []int32{
	0, // 0: agentcage.vault.v1.VaultService.PutSecret:input_type -> agentcage.vault.v1.PutSecretRequest
	2, // 1: agentcage.vault.v1.VaultService.GetSecret:input_type -> agentcage.vault.v1.GetSecretRequest
	4, // 2: agentcage.vault.v1.VaultService.ListSecrets:input_type -> agentcage.vault.v1.ListSecretsRequest
	6, // 3: agentcage.vault.v1.VaultService.DeleteSecret:input_type -> agentcage.vault.v1.DeleteSecretRequest
	1, // 4: agentcage.vault.v1.VaultService.PutSecret:output_type -> agentcage.vault.v1.PutSecretResponse
	3, // 5: agentcage.vault.v1.VaultService.GetSecret:output_type -> agentcage.vault.v1.GetSecretResponse
	5, // 6: agentcage.vault.v1.VaultService.ListSecrets:output_type -> agentcage.vault.v1.ListSecretsResponse
	7, // 7: agentcage.vault.v1.VaultService.DeleteSecret:output_type -> agentcage.vault.v1.DeleteSecretResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_vault_proto_init() }
func file_api_proto_vault_proto_init() {
	if File_api_proto_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_vault_proto_rawDesc), len(file_api_proto_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_vault_proto_goTypes,
		DependencyIndexes: file_api_proto_vault_proto_depIdxs,
		MessageInfos:      file_api_proto_vault_proto_msgTypes,
	}.Build()
	File_api_proto_vault_proto = out.File
	file_api_proto_vault_proto_goTypes = nil
	file_api_proto_vault_proto_depIdxs = nil
}
