{{- if .Values.spire.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-spire-agent
  labels:
    app: agentcage-spire-agent
spec:
  selector:
    matchLabels:
      app: agentcage-spire-agent
  template:
    metadata:
      labels:
        app: agentcage-spire-agent
    spec:
      containers:
        - name: spire-agent
          image: "{{ .Values.spire.agent.image.repository }}:{{ .Values.spire.agent.image.tag }}"
          args: ["-config", "/etc/spire/agent.conf"]
          volumeMounts:
            - name: config
              mountPath: /etc/spire
              readOnly: true
            - name: socket
              mountPath: /run/spire
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-spire-agent-config
        - name: socket
          hostPath:
            path: /run/spire
            type: DirectoryOrCreate
{{- end }}
